# -*- coding: utf-8 -*-
"""ESM-2-GylcometabolicProteinIndependent_test27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1fpb24SPqltxK7IHIz-B86qpZV5OyI7
"""

"""
CNN-Transformer Independent Test Model
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Split   : 80% Train / 20% Independent Test (stratified, random_state=42)
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_cnntransformer, tpr_cnntransformer, roc_auc_cnntransformer
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, matthews_corrcoef, confusion_matrix,
                              roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load data
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

X = df.drop(columns=["Label"]).values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# PVC (physicochemical count-based) descriptors can reach extreme magnitudes
# (e.g. 1e+130+) while ESM-2 embedding features are small signed floats.
# A signed-log transform compresses the huge dynamic range without breaking
# sign information, and prevents float32 overflow before scaling.
X = np.sign(X) * np.log1p(np.abs(X))
X = X.astype("float32")

# ----------------------------------------------------------------------
# 2. Train / Independent-test split (80/20, stratified)
# ----------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# ----------------------------------------------------------------------
# 3. Feature scaling (fit ONLY on train, applied to test -> no leakage)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# reshape to (samples, timesteps, channels) for Conv1D
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

n_features = X_train.shape[1]

# ----------------------------------------------------------------------
# 4. Transformer encoder block
# ----------------------------------------------------------------------
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.2):
    x = layers.LayerNormalization(epsilon=1e-6)(inputs)
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(x, x)
    x = layers.Dropout(dropout)(x)
    res = x + inputs

    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(x)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=res.shape[-1], kernel_size=1)(x)
    return x + res


# ----------------------------------------------------------------------
# 5. Build CNN-Transformer model
# ----------------------------------------------------------------------
def build_cnn_transformer(input_len):
    inputs = layers.Input(shape=(input_len, 1))

    # --- CNN feature extraction ---
    x = layers.Conv1D(64, kernel_size=7, padding="same", activation="relu")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    x = layers.Conv1D(128, kernel_size=5, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    x = layers.Conv1D(128, kernel_size=3, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    # --- Transformer encoder blocks ---
    for _ in range(2):
        x = transformer_encoder(x, head_size=64, num_heads=4, ff_dim=128, dropout=0.2)

    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    cnn_transformer = models.Model(inputs, outputs, name="CNN_Transformer")
    cnn_transformer.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return cnn_transformer


cnn_transformer = build_cnn_transformer(n_features)
cnn_transformer.summary()

# ----------------------------------------------------------------------
# 6. Train
# ----------------------------------------------------------------------
early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=15, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=7, min_lr=1e-6
)

history = cnn_transformer.fit(
    X_train, y_train,
    validation_split=0.1,          # carved out of the training set only
    batch_size=32,
    epochs=100,
    callbacks=[early_stop, reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 7. Independent test evaluation
# ----------------------------------------------------------------------
y_pred_prob = cnn_transformer.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = recall_score(y_test, y_pred)               # = TPR / recall
specificity = tn / (tn + fp)
precision   = precision_score(y_test, y_pred)
f1          = f1_score(y_test, y_pred)
mcc         = matthews_corrcoef(y_test, y_pred)
auc_score   = roc_auc_score(y_test, y_pred_prob)

print("\n================ Independent Test Results (CNN-Transformer) ================")
print(f"Accuracy    : {accuracy*100:.2f}%")
print(f"Sensitivity : {sensitivity*100:.2f}%")
print(f"Specificity : {specificity*100:.2f}%")
print(f"Precision   : {precision*100:.2f}%")
print(f"F1-score    : {f1*100:.2f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==============================================================================")

# ----------------------------------------------------------------------
# 8. ROC Curve (variable names as requested)
# ----------------------------------------------------------------------
fpr_cnntransformer, tpr_cnntransformer, thresholds_cnntransformer = roc_curve(
    y_test, y_pred_prob
)
roc_auc_cnntransformer = auc(fpr_cnntransformer, tpr_cnntransformer)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_cnntransformer,
    tpr_cnntransformer,
    color="darkorange",
    lw=2,
    label=f"CNN-Transformer (AUC = {roc_auc_cnntransformer:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - CNN-Transformer (Independent Test)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_CNN_Transformer_Independent.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 9. Save metrics to CSV
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "CNN-Transformer",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_cnntransformer,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("CNN_Transformer_Independent_Results.csv", index=False)
print("\nSaved: CNN_Transformer_Independent_Results.csv")
print("Saved: ROC_CNN_Transformer_Independent.png")

# ----------------------------------------------------------------------
# 10. Save ROC values (for combining with other models later)
# ----------------------------------------------------------------------
np.savez(
    "roc_values_cnntransformer.npz",
    fpr_cnntransformer=fpr_cnntransformer,
    tpr_cnntransformer=tpr_cnntransformer,
    roc_auc_cnntransformer=roc_auc_cnntransformer,
)
print("Saved: roc_values_cnntransformer.npz")



"""
KAN (Kolmogorov-Arnold Network) - Independent Test Model
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Split   : 80% Train / 20% Independent Test (stratified, random_state=42)
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_kan, tpr_kan, roc_auc_kan

Implementation note:
TensorFlow/Keras has no built-in KAN layer, so a Chebyshev-polynomial KAN
layer (ChebyKAN) is implemented from scratch below. Instead of a fixed
weight * fixed-activation (as in a normal Dense layer), each edge learns
its own univariate function, approximated as a weighted sum of Chebyshev
polynomials — this is the core idea of Kolmogorov-Arnold Networks.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, matthews_corrcoef, confusion_matrix,
                              roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load data
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

X = df.drop(columns=["Label"]).values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# PVC (physicochemical count-based) descriptors can reach extreme magnitudes
# (e.g. 1e+130+) while ESM-2 embedding features are small signed floats.
# A signed-log transform compresses the huge dynamic range without breaking
# sign information, and prevents float32 overflow before scaling.
X = np.sign(X) * np.log1p(np.abs(X))
X = X.astype("float32")

# ----------------------------------------------------------------------
# 2. Train / Independent-test split (80/20, stratified)
# ----------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# ----------------------------------------------------------------------
# 3. Feature scaling (fit ONLY on train, applied to test -> no leakage)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

n_features = X_train.shape[1]

# ----------------------------------------------------------------------
# 4. ChebyKAN layer  (Kolmogorov-Arnold layer via Chebyshev polynomials)
# ----------------------------------------------------------------------
class ChebyKANLayer(layers.Layer):
    """
    Kolmogorov-Arnold layer: replaces (linear-weight + fixed-activation)
    with a learnable univariate function per (input, output) edge,
    expanded in a Chebyshev polynomial basis of a given degree.
    """
    def __init__(self, out_features, degree=4, **kwargs):
        super().__init__(**kwargs)
        self.out_features = out_features
        self.degree = degree

    def build(self, input_shape):
        in_features = int(input_shape[-1])
        self.in_features = in_features
        # coeffs[i, o, d] = coefficient of Chebyshev poly degree d for edge (i -> o)
        self.coeffs = self.add_weight(
            name="cheby_coeffs",
            shape=(in_features, self.out_features, self.degree + 1),
            initializer=tf.keras.initializers.RandomNormal(
                mean=0.0, stddev=1.0 / (in_features * (self.degree + 1))
            ),
            trainable=True,
        )
        self.bias = self.add_weight(
            name="bias",
            shape=(self.out_features,),
            initializer="zeros",
            trainable=True,
        )

    def call(self, x):
        # squash inputs into [-1, 1], the valid domain of Chebyshev polynomials
        x = tf.tanh(x)

        # build Chebyshev basis T_0..T_degree via the recurrence
        # T_0 = 1, T_1 = x, T_k = 2*x*T_{k-1} - T_{k-2}
        basis = [tf.ones_like(x), x]
        for _ in range(2, self.degree + 1):
            basis.append(2.0 * x * basis[-1] - basis[-2])
        basis = tf.stack(basis, axis=-1)          # (batch, in_features, degree+1)

        # combine per-edge learned functions -> output units
        out = tf.einsum("bid,iod->bo", basis, self.coeffs)
        return out + self.bias

    def get_config(self):
        config = super().get_config()
        config.update({"out_features": self.out_features, "degree": self.degree})
        return config


# ----------------------------------------------------------------------
# 5. Build KAN model
# ----------------------------------------------------------------------
def build_kan(input_dim, degree=4):
    inputs = layers.Input(shape=(input_dim,))

    x = ChebyKANLayer(256, degree=degree)(inputs)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = ChebyKANLayer(64, degree=degree)(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(0.2)(x)

    x = ChebyKANLayer(16, degree=degree)(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(0.1)(x)

    outputs = layers.Dense(1, activation="sigmoid")(x)

    kan = models.Model(inputs, outputs, name="KAN")
    kan.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return kan


kan = build_kan(n_features, degree=4)
kan.summary()

# ----------------------------------------------------------------------
# 6. Train
# ----------------------------------------------------------------------
early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=15, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=7, min_lr=1e-6
)

history = kan.fit(
    X_train, y_train,
    validation_split=0.1,          # carved out of the training set only
    batch_size=32,
    epochs=100,
    callbacks=[early_stop, reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 7. Independent test evaluation
# ----------------------------------------------------------------------
y_pred_prob = kan.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = recall_score(y_test, y_pred)               # = TPR / recall
specificity = tn / (tn + fp)
precision   = precision_score(y_test, y_pred)
f1          = f1_score(y_test, y_pred)
mcc         = matthews_corrcoef(y_test, y_pred)
auc_score   = roc_auc_score(y_test, y_pred_prob)

print("\n===================== Independent Test Results (KAN) =======================")
print(f"Accuracy    : {accuracy*100:.4f}%")
print(f"Sensitivity : {sensitivity*100:.4f}%")
print(f"Specificity : {specificity*100:.4f}%")
print(f"Precision   : {precision*100:.4f}%")
print(f"F1-score    : {f1*100:.4f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==============================================================================")

# ----------------------------------------------------------------------
# 8. ROC Curve (variable names as requested)
# ----------------------------------------------------------------------
fpr_kan, tpr_kan, thresholds_kan = roc_curve(y_test, y_pred_prob)
roc_auc_kan = auc(fpr_kan, tpr_kan)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_kan,
    tpr_kan,
    color="green",
    lw=2,
    label=f"KAN (AUC = {roc_auc_kan:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - KAN (Independent Test)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_KAN_Independent.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 9. Save metrics to CSV
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "KAN",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_kan,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("KAN_Independent_Results.csv", index=False)
print("\nSaved: KAN_Independent_Results.csv")
print("Saved: ROC_KAN_Independent.png")

# ----------------------------------------------------------------------
# 10. Save ROC values (for combining with other models later)
# ----------------------------------------------------------------------
np.savez(
    "roc_values_kan.npz",
    fpr_kan=fpr_kan,
    tpr_kan=tpr_kan,
    roc_auc_kan=roc_auc_kan,
)
print("Saved: roc_values_kan.npz")



"""
Capsule Hybrid Network (CNN1D + Primary Capsules + Dynamic-Routing Capsules)
Independent Test Model
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Split   : 80% Train / 20% Independent Test (stratified, random_state=42)
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_capsule, tpr_capsule, roc_auc_capsule

Architecture ("hybrid" = CNN front-end + Capsule Network back-end):
    raw features -> Conv1D blocks (local feature extraction, downsampling)
                 -> Primary Capsule layer (groups conv features into vectors)
                 -> Digit/Class Capsule layer (dynamic routing-by-agreement)
                 -> capsule vector lengths -> softmax -> class probability

IMPORTANT NOTE (please read):
    No legitimate script can *guarantee* a fixed accuracy (e.g. 94%) on an
    independent test set -- the real number depends on how separable the
    two classes actually are in this feature space. This script uses solid
    practices (proper scaling with no leakage, early stopping, LR schedule,
    dynamic routing) to get the best genuine result the data supports.
    Please report whatever number it actually produces.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, matthews_corrcoef, confusion_matrix,
                              roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load data
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# PVC descriptors can reach extreme magnitudes (1e+100+) while ESM-2
# embedding features are small signed floats. arcsinh (signed-log) tames
# the huge dynamic range without breaking sign, and prevents float32
# overflow before scaling.
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Train / Independent-test split (80/20, stratified)
# ----------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# ----------------------------------------------------------------------
# 3. Feature scaling (fit ONLY on train, applied to test -> no leakage)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# reshape to (samples, timesteps, channels) for Conv1D
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1).astype("float32")
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1).astype("float32")

n_features = X_train.shape[1]

# ----------------------------------------------------------------------
# 4. Capsule Network building blocks
# ----------------------------------------------------------------------
def squash(vectors, axis=-1, epsilon=1e-7):
    """Non-linear squashing so capsule vector length in [0,1) represents
    the probability that the entity it represents is present."""
    s_squared_norm = tf.reduce_sum(tf.square(vectors), axis=axis, keepdims=True)
    scale = s_squared_norm / (1.0 + s_squared_norm) / tf.sqrt(s_squared_norm + epsilon)
    return scale * vectors


class PrimaryCapsule(layers.Layer):
    """Conv1D -> reshape into a set of low-level capsule vectors -> squash."""
    def __init__(self, num_channels, dim_capsule, kernel_size=3, strides=2, **kwargs):
        super().__init__(**kwargs)
        self.num_channels = num_channels
        self.dim_capsule = dim_capsule
        self.kernel_size = kernel_size
        self.strides = strides
        self.conv = layers.Conv1D(
            filters=num_channels * dim_capsule,
            kernel_size=kernel_size,
            strides=strides,
            padding="valid",
            activation="relu",
        )

    def call(self, inputs):
        x = self.conv(inputs)                                    # (b, t, channels*dim)
        t = tf.shape(x)[1]
        x = tf.reshape(x, (-1, t * self.num_channels, self.dim_capsule))
        return squash(x)

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_channels": self.num_channels,
            "dim_capsule": self.dim_capsule,
            "kernel_size": self.kernel_size,
            "strides": self.strides,
        })
        return config


class CapsuleRoutingLayer(layers.Layer):
    """Higher-level capsule layer with dynamic routing-by-agreement."""
    def __init__(self, num_capsules, dim_capsule, routings=3, **kwargs):
        super().__init__(**kwargs)
        self.num_capsules = num_capsules
        self.dim_capsule = dim_capsule
        self.routings = routings

    def build(self, input_shape):
        self.input_num_capsules = int(input_shape[1])
        self.input_dim_capsule = int(input_shape[2])
        # transformation matrices: one per (input_capsule, output_capsule) pair
        self.W = self.add_weight(
            shape=(self.input_num_capsules, self.num_capsules,
                   self.dim_capsule, self.input_dim_capsule),
            initializer="glorot_uniform",
            name="routing_weights",
            trainable=True,
        )

    def call(self, inputs):
        # inputs: (batch, input_num_capsules, input_dim_capsule)
        # u_hat: prediction vectors from every input capsule to every output capsule
        u_hat = tf.einsum("bic,ikdc->bikd", inputs, self.W)
        u_hat_stopped = tf.stop_gradient(u_hat)

        batch_size = tf.shape(inputs)[0]
        b = tf.zeros((batch_size, self.input_num_capsules, self.num_capsules))

        v = None
        for r in range(self.routings):
            c = tf.nn.softmax(b, axis=2)                       # coupling coefficients
            use_hat = u_hat if r == self.routings - 1 else u_hat_stopped
            s = tf.einsum("bik,bikd->bkd", c, use_hat)
            v = squash(s)
            if r < self.routings - 1:
                b += tf.einsum("bkd,bikd->bik", v, use_hat)
        return v                                               # (batch, num_capsules, dim_capsule)

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_capsules": self.num_capsules,
            "dim_capsule": self.dim_capsule,
            "routings": self.routings,
        })
        return config


class CapsuleLength(layers.Layer):
    """Length of each output capsule vector = class 'presence' score."""
    def call(self, inputs):
        return tf.sqrt(tf.reduce_sum(tf.square(inputs), axis=-1) + 1e-7)


# ----------------------------------------------------------------------
# 5. Build Capsule Hybrid Network
# ----------------------------------------------------------------------
def build_capsule_hybrid(input_len):
    inputs = layers.Input(shape=(input_len, 1))

    # ---- CNN front-end: local feature extraction + downsampling ----
    x = layers.Conv1D(64, kernel_size=9, padding="same", activation="relu")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=4)(x)

    x = layers.Conv1D(128, kernel_size=5, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=4)(x)

    x = layers.Conv1D(128, kernel_size=3, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=2)(x)
    x = layers.Dropout(0.3)(x)

    # ---- Capsule back-end ----
    x = PrimaryCapsule(num_channels=16, dim_capsule=8, kernel_size=3, strides=2)(x)
    x = CapsuleRoutingLayer(num_capsules=2, dim_capsule=16, routings=3)(x)  # 2 class-capsules
    lengths = CapsuleLength()(x)                      # (batch, 2) -> presence score per class
    outputs = layers.Softmax(name="class_probabilities")(lengths)

    capsule_hybrid = models.Model(inputs, outputs, name="Capsule_Hybrid_Network")
    capsule_hybrid.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return capsule_hybrid


capsule_hybrid = build_capsule_hybrid(n_features)
capsule_hybrid.summary()

# ----------------------------------------------------------------------
# 6. Train
# ----------------------------------------------------------------------
early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=15, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=7, min_lr=1e-6
)

history = capsule_hybrid.fit(
    X_train, y_train,
    validation_split=0.1,          # carved out of the training set only
    batch_size=32,
    epochs=100,
    callbacks=[early_stop, reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 7. Independent test evaluation
# ----------------------------------------------------------------------
y_prob_both = capsule_hybrid.predict(X_test)          # (n, 2) class probabilities
y_pred_prob = y_prob_both[:, 1]                       # probability of class 1
y_pred = np.argmax(y_prob_both, axis=1)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = recall_score(y_test, y_pred)               # = TPR / recall
specificity = tn / (tn + fp)
precision   = precision_score(y_test, y_pred)
f1          = f1_score(y_test, y_pred)
mcc         = matthews_corrcoef(y_test, y_pred)
auc_score   = roc_auc_score(y_test, y_pred_prob)

print("\n================ Independent Test Results (Capsule Hybrid) =================")
print(f"Accuracy    : {accuracy*100:.2f}%")
print(f"Sensitivity : {sensitivity*100:.2f}%")
print(f"Specificity : {specificity*100:.2f}%")
print(f"Precision   : {precision*100:.2f}%")
print(f"F1-score    : {f1*100:.2f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==============================================================================")

# ----------------------------------------------------------------------
# 8. ROC Curve (variable names as requested)
# ----------------------------------------------------------------------
fpr_capsule, tpr_capsule, thresholds_capsule = roc_curve(y_test, y_pred_prob)
roc_auc_capsule = auc(fpr_capsule, tpr_capsule)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_capsule,
    tpr_capsule,
    color="crimson",
    lw=2,
    label=f"Capsule Hybrid Network (AUC = {roc_auc_capsule:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Capsule Hybrid Network (Independent Test)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_Capsule_Hybrid_Independent.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 9. Save metrics to CSV
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "Capsule_Hybrid_Network",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_capsule,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("Capsule_Hybrid_Independent_Results.csv", index=False)
print("\nSaved: Capsule_Hybrid_Independent_Results.csv")
print("Saved: ROC_Capsule_Hybrid_Independent.png")

# ----------------------------------------------------------------------
# 10. Save ROC values (for combining with other models later)
# ----------------------------------------------------------------------
np.savez(
    "roc_values_capsule.npz",
    fpr_capsule=fpr_capsule,
    tpr_capsule=tpr_capsule,
    roc_auc_capsule=roc_auc_capsule,
)
print("Saved: roc_values_capsule.npz")



"""
Siamese Contrastive Network - Independent Test Model
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Split   : 80% Train / 20% Independent Test (stratified, random_state=42)
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_siamese, tpr_siamese, roc_auc_siamese

How it works:
    1. A shared "twin" encoder network maps every sample to an embedding
       vector. The same encoder weights are used for both inputs of a pair
       (that's what makes it "Siamese").
    2. The network is trained on PAIRS of samples with a contrastive loss:
       pairs from the SAME class are pulled together in embedding space,
       pairs from DIFFERENT classes are pushed apart (beyond a margin).
    3. After training, each training sample's embedding is computed, and
       a class "prototype" (centroid) is built for class 0 and class 1.
    4. Independent test samples are classified by which prototype their
       embedding is closer to; the distance difference is converted into
       a probability score for ROC/AUC.

IMPORTANT NOTE (please read):
    No legitimate script can *guarantee* a fixed accuracy on an independent
    test set -- the real number depends on how separable the two classes
    actually are in this feature space. This script follows solid practice
    (train-only pair sampling and prototypes, no test leakage, early
    stopping, LR scheduling) to get the best genuine result the data
    supports. Please report whatever number it actually produces.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, matthews_corrcoef, confusion_matrix,
                              roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
rng = np.random.default_rng(SEED)

# ----------------------------------------------------------------------
# 1. Load data
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# PVC descriptors can reach extreme magnitudes (1e+100+) while ESM-2
# embedding features are small signed floats. arcsinh (signed-log) tames
# the huge dynamic range without breaking sign, and prevents float32
# overflow before scaling.
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Train / Independent-test split (80/20, stratified)
# ----------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# ----------------------------------------------------------------------
# 3. Feature scaling (fit ONLY on train, applied to test -> no leakage)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype("float32")
X_test = scaler.transform(X_test).astype("float32")

n_features = X_train.shape[1]

# ----------------------------------------------------------------------
# 4. Pair generation (built ONLY from the training set)
# ----------------------------------------------------------------------
def make_pairs(X, y, pairs_per_sample=2, rng=rng):
    """For every sample, create `pairs_per_sample` positive (same-class)
    and `pairs_per_sample` negative (different-class) pairs."""
    class0_idx = np.where(y == 0)[0]
    class1_idx = np.where(y == 1)[0]
    idx_by_class = {0: class0_idx, 1: class1_idx}

    left, right, labels = [], [], []
    n = len(y)
    for i in range(n):
        cls = y[i]
        same_pool = idx_by_class[cls]
        diff_pool = idx_by_class[1 - cls]

        # positive (similar) pairs
        for _ in range(pairs_per_sample):
            j = rng.choice(same_pool)
            left.append(i); right.append(j); labels.append(1)

        # negative (dissimilar) pairs
        for _ in range(pairs_per_sample):
            j = rng.choice(diff_pool)
            left.append(i); right.append(j); labels.append(0)

    left, right, labels = np.array(left), np.array(right), np.array(labels)
    perm = rng.permutation(len(labels))
    left, right, labels = left[perm], right[perm], labels[perm]
    return X[left], X[right], labels.astype("float32")


X_left, X_right, pair_labels = make_pairs(X_train, y_train, pairs_per_sample=2)
print(f"Generated training pairs: {X_left.shape[0]} "
      f"(similar={int(pair_labels.sum())}, dissimilar={int((1-pair_labels).sum())})")

# ----------------------------------------------------------------------
# 5. Shared twin encoder
# ----------------------------------------------------------------------
EMBED_DIM = 64

def build_encoder(input_dim, embed_dim=EMBED_DIM):
    inputs = layers.Input(shape=(input_dim,))
    x = layers.Dense(512, activation="relu")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(256, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.2)(x)

    embeddings = layers.Dense(embed_dim, activation=None, name="embedding")(x)
    # L2-normalize embeddings -> distances are bounded and well-behaved
    embeddings = layers.Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(embeddings)
    return models.Model(inputs, embeddings, name="Twin_Encoder")


encoder = build_encoder(n_features)
encoder.summary()

# ----------------------------------------------------------------------
# 6. Siamese network (shared weights) + contrastive loss
# ----------------------------------------------------------------------
def euclidean_distance(vectors):
    x, y_ = vectors
    sum_sq = tf.reduce_sum(tf.square(x - y_), axis=1, keepdims=True)
    return tf.sqrt(tf.maximum(sum_sq, 1e-9))


def contrastive_loss(margin=1.0):
    def loss(y_true, y_pred):
        y_true = tf.cast(y_true, y_pred.dtype)
        square_pred = tf.square(y_pred)
        margin_square = tf.square(tf.maximum(margin - y_pred, 0.0))
        return tf.reduce_mean(y_true * square_pred + (1.0 - y_true) * margin_square)
    return loss


input_a = layers.Input(shape=(n_features,), name="input_a")
input_b = layers.Input(shape=(n_features,), name="input_b")

embed_a = encoder(input_a)
embed_b = encoder(input_b)

distance = layers.Lambda(euclidean_distance, name="euclidean_distance")([embed_a, embed_b])

siamese_contrastive = models.Model(inputs=[input_a, input_b], outputs=distance,
                                    name="Siamese_Contrastive_Network")
siamese_contrastive.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss=contrastive_loss(margin=1.0),
)
siamese_contrastive.summary()

# ----------------------------------------------------------------------
# 7. Train
# ----------------------------------------------------------------------
early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=15, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=7, min_lr=1e-6
)

history = siamese_contrastive.fit(
    [X_left, X_right], pair_labels,
    validation_split=0.1,          # carved out of the training pairs only
    batch_size=32,
    epochs=100,
    callbacks=[early_stop, reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 8. Build class prototypes from TRAINING embeddings only
# ----------------------------------------------------------------------
train_embeddings = encoder.predict(X_train, batch_size=256)
prototype_0 = train_embeddings[y_train == 0].mean(axis=0)
prototype_1 = train_embeddings[y_train == 1].mean(axis=0)

# ----------------------------------------------------------------------
# 9. Independent test evaluation
# ----------------------------------------------------------------------
test_embeddings = encoder.predict(X_test, batch_size=256)

dist_to_0 = np.linalg.norm(test_embeddings - prototype_0, axis=1)
dist_to_1 = np.linalg.norm(test_embeddings - prototype_1, axis=1)

y_pred = (dist_to_1 < dist_to_0).astype(int)            # closer prototype wins
# turn the distance margin into a bounded probability-like score for ROC/AUC
y_pred_prob = tf.sigmoid(dist_to_0 - dist_to_1).numpy()

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = recall_score(y_test, y_pred)               # = TPR / recall
specificity = tn / (tn + fp)
precision   = precision_score(y_test, y_pred)
f1          = f1_score(y_test, y_pred)
mcc         = matthews_corrcoef(y_test, y_pred)
auc_score   = roc_auc_score(y_test, y_pred_prob)

print("\n============= Independent Test Results (Siamese Contrastive) ===============")
print(f"Accuracy    : {accuracy*100:.2f}%")
print(f"Sensitivity : {sensitivity*100:.2f}%")
print(f"Specificity : {specificity*100:.2f}%")
print(f"Precision   : {precision*100:.2f}%")
print(f"F1-score    : {f1*100:.2f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==============================================================================")

# ----------------------------------------------------------------------
# 10. ROC Curve (variable names as requested)
# ----------------------------------------------------------------------
fpr_siamese, tpr_siamese, thresholds_siamese = roc_curve(y_test, y_pred_prob)
roc_auc_siamese = auc(fpr_siamese, tpr_siamese)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_siamese,
    tpr_siamese,
    color="teal",
    lw=2,
    label=f"Siamese Contrastive (AUC = {roc_auc_siamese:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Siamese Contrastive Network (Independent Test)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_Siamese_Contrastive_Independent.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 11. Save metrics to CSV
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "Siamese_Contrastive_Network",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_siamese,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("Siamese_Contrastive_Independent_Results.csv", index=False)
print("\nSaved: Siamese_Contrastive_Independent_Results.csv")
print("Saved: ROC_Siamese_Contrastive_Independent.png")

# ----------------------------------------------------------------------
# 12. Save ROC values (for combining with other models later)
# ----------------------------------------------------------------------
np.savez(
    "roc_values_siamese.npz",
    fpr_siamese=fpr_siamese,
    tpr_siamese=tpr_siamese,
    roc_auc_siamese=roc_auc_siamese,
)
print("Saved: roc_values_siamese.npz")



"""
Mamba-2 (Selective State-Space Model) - Independent Test Model
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Split   : 80% Train / 20% Independent Test (stratified, random_state=42)
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_mamba, tpr_mamba, roc_auc_mamba

IMPLEMENTATION NOTE (please read):
    There is no official Mamba-2 layer in TensorFlow/Keras (the reference
    implementation uses custom CUDA kernels). This script implements the
    Mamba-2 recurrence -- a SELECTIVE state-space model (SSM) -- from
    scratch with plain TensorFlow ops, following the key architectural
    idea that distinguishes Mamba-2 from Mamba-1:

        Mamba-1 : the state matrix A is a full diagonal, independent
                  per (channel, state) pair.
        Mamba-2 : A is a single SCALAR per channel (shared across all
                  state dimensions) -- the "state-space duality" (SSD)
                  simplification that makes Mamba-2 cheaper and lets it
                  be viewed as a form of structured attention.

    That scalar-per-channel A is exactly what is implemented below,
    together with: input-dependent (selective) discretization step size
    (delta), input-dependent B/C projections, a depthwise causal Conv1D
    "short local context" step, and a gated output (SiLU-gated residual)
    -- all standard Mamba-2 block components.

    Because raw per-timestep recurrence for 1433 steps is expensive on
    CPU, a small CNN front-end first downsamples the sequence (same
    pattern used in the other scripts here) before the Mamba-2 blocks.

IMPORTANT NOTE ON ACCURACY (please read):
    No legitimate script can *guarantee* a fixed accuracy on an independent
    test set -- the real number depends on how separable the two classes
    actually are in this feature space. This script follows solid practice
    (no leakage, early stopping, LR scheduling) to get the best genuine
    result the data supports. Please report whatever number it actually
    produces.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, matthews_corrcoef, confusion_matrix,
                              roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load data
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# PVC descriptors can reach extreme magnitudes (1e+100+) while ESM-2
# embedding features are small signed floats. arcsinh (signed-log) tames
# the huge dynamic range without breaking sign, and prevents float32
# overflow before scaling.
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Train / Independent-test split (80/20, stratified)
# ----------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# ----------------------------------------------------------------------
# 3. Feature scaling (fit ONLY on train, applied to test -> no leakage)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype("float32")
X_test = scaler.transform(X_test).astype("float32")

# reshape to (samples, timesteps, channels) for Conv1D front-end
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

n_features = X_train.shape[1]

# ----------------------------------------------------------------------
# 4. Mamba-2 style block (selective SSM with scalar-per-channel A)
# ----------------------------------------------------------------------
class Mamba2Block(layers.Layer):
    def __init__(self, d_model, d_state=16, d_conv=4, expand=2, **kwargs):
        super().__init__(**kwargs)
        self.d_model = d_model
        self.d_state = d_state
        self.d_conv = d_conv
        self.d_inner = expand * d_model

    def build(self, input_shape):
        self.in_proj = layers.Dense(2 * self.d_inner, use_bias=False, name="in_proj")
        self.conv1d = layers.Conv1D(
            filters=self.d_inner, kernel_size=self.d_conv,
            padding="causal", groups=self.d_inner, activation=None, name="short_conv"
        )
        # produces: delta (1), B (d_state), C (d_state) per timestep, per input
        self.x_proj = layers.Dense(1 + 2 * self.d_state, use_bias=False, name="x_proj")
        self.dt_proj = layers.Dense(self.d_inner, use_bias=True, name="dt_proj")

        # Mamba-2: A is a single learnable SCALAR per channel (not per state)
        self.A_log = self.add_weight(
            shape=(self.d_inner,), initializer=tf.keras.initializers.Constant(0.0),
            trainable=True, name="A_log"
        )
        self.D = self.add_weight(
            shape=(self.d_inner,), initializer="ones", trainable=True, name="skip_D"
        )
        self.out_proj = layers.Dense(self.d_model, use_bias=False, name="out_proj")
        super().build(input_shape)

    def call(self, x):
        # x: (batch, seq_len, d_model)
        seq_len = tf.shape(x)[1]

        x_and_res = self.in_proj(x)                        # (b, L, 2*d_inner)
        x_in, res = tf.split(x_and_res, 2, axis=-1)

        x_in = self.conv1d(x_in)[:, :seq_len, :]            # causal short local context
        x_in = tf.nn.silu(x_in)                              # (b, L, d_inner)

        x_dbl = self.x_proj(x_in)                            # (b, L, 1+2*d_state)
        delta, B, C = tf.split(x_dbl, [1, self.d_state, self.d_state], axis=-1)
        delta = tf.nn.softplus(self.dt_proj(delta))          # (b, L, d_inner) - selective step size

        A = -tf.exp(self.A_log)                               # (d_inner,) scalar per channel

        # discretization (Mamba-2 SSD simplification: scalar A broadcasts over d_state)
        deltaA = tf.exp(delta * A)                            # (b, L, d_inner)
        deltaB_u = (delta * x_in)[..., None] * B[:, :, None, :]   # (b, L, d_inner, d_state)

        deltaA_seq = tf.transpose(deltaA, [1, 0, 2])          # (L, b, d_inner)
        deltaBu_seq = tf.transpose(deltaB_u, [1, 0, 2, 3])    # (L, b, d_inner, d_state)

        def scan_step(h_prev, elems):
            dA_t, dBu_t = elems                               # dA_t:(b,d_inner) dBu_t:(b,d_inner,d_state)
            return dA_t[..., None] * h_prev + dBu_t

        h0 = tf.zeros((tf.shape(x)[0], self.d_inner, self.d_state), dtype=x.dtype)
        hs = tf.scan(scan_step, (deltaA_seq, deltaBu_seq), initializer=h0)  # (L,b,d_inner,d_state)
        hs = tf.transpose(hs, [1, 0, 2, 3])                    # (b, L, d_inner, d_state)

        y = tf.reduce_sum(hs * C[:, :, None, :], axis=-1)      # (b, L, d_inner)
        y = y + x_in * self.D                                  # skip connection
        y = y * tf.nn.silu(res)                                # output gate
        return self.out_proj(y)                                # (b, L, d_model)

    def get_config(self):
        config = super().get_config()
        config.update({
            "d_model": self.d_model, "d_state": self.d_state,
            "d_conv": self.d_conv, "expand": self.d_inner // self.d_model,
        })
        return config


# ----------------------------------------------------------------------
# 5. Build Mamba-2 hybrid model
# ----------------------------------------------------------------------
def build_mamba2(input_len, d_model=64, d_state=16, n_blocks=2):
    inputs = layers.Input(shape=(input_len, 1))

    # ---- CNN front-end: downsample the long 1433-step sequence ----
    x = layers.Conv1D(32, kernel_size=9, padding="same", activation="relu")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=4)(x)

    x = layers.Conv1D(64, kernel_size=5, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=4)(x)
    x = layers.Dropout(0.2)(x)

    # ---- project into Mamba-2 model dimension ----
    x = layers.Dense(d_model)(x)

    for _ in range(n_blocks):
        residual = x
        x = layers.LayerNormalization(epsilon=1e-6)(x)
        x = Mamba2Block(d_model=d_model, d_state=d_state)(x)
        x = layers.Dropout(0.2)(x)
        x = x + residual

    x = layers.LayerNormalization(epsilon=1e-6)(x)
    x = layers.GlobalAveragePooling1D()(x)

    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    mamba2 = models.Model(inputs, outputs, name="Mamba2_Model")
    mamba2.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return mamba2


mamba2 = build_mamba2(n_features)
mamba2.summary()

# ----------------------------------------------------------------------
# 6. Train
# ----------------------------------------------------------------------
early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=15, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=7, min_lr=1e-6
)

history = mamba2.fit(
    X_train, y_train,
    validation_split=0.1,          # carved out of the training set only
    batch_size=32,
    epochs=100,
    callbacks=[early_stop, reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 7. Independent test evaluation
# ----------------------------------------------------------------------
y_pred_prob = mamba2.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = recall_score(y_test, y_pred)               # = TPR / recall
specificity = tn / (tn + fp)
precision   = precision_score(y_test, y_pred)
f1          = f1_score(y_test, y_pred)
mcc         = matthews_corrcoef(y_test, y_pred)
auc_score   = roc_auc_score(y_test, y_pred_prob)

print("\n=================== Independent Test Results (Mamba-2) ======================")
print(f"Accuracy    : {accuracy*100:.2f}%")
print(f"Sensitivity : {sensitivity*100:.2f}%")
print(f"Specificity : {specificity*100:.2f}%")
print(f"Precision   : {precision*100:.2f}%")
print(f"F1-score    : {f1*100:.2f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==============================================================================")

# ----------------------------------------------------------------------
# 8. ROC Curve (variable names as requested)
# ----------------------------------------------------------------------
fpr_mamba, tpr_mamba, thresholds_mamba = roc_curve(y_test, y_pred_prob)
roc_auc_mamba = auc(fpr_mamba, tpr_mamba)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_mamba,
    tpr_mamba,
    color="purple",
    lw=2,
    label=f"Mamba-2 (AUC = {roc_auc_mamba:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Mamba-2 (Independent Test)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_Mamba2_Independent.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 9. Save metrics to CSV
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "Mamba2",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_mamba,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("Mamba2_Independent_Results.csv", index=False)
print("\nSaved: Mamba2_Independent_Results.csv")
print("Saved: ROC_Mamba2_Independent.png")

# ----------------------------------------------------------------------
# 10. Save ROC values (for combining with other models later)
# ----------------------------------------------------------------------
np.savez(
    "roc_values_mamba2.npz",
    fpr_mamba=fpr_mamba,
    tpr_mamba=tpr_mamba,
    roc_auc_mamba=roc_auc_mamba,
)
print("Saved: roc_values_mamba2.npz")



"""
xLSTM (Extended Long Short-Term Memory) - Independent Test Model
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Split   : 80% Train / 20% Independent Test (stratified, random_state=42)
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_xlstm, tpr_xlstm, roc_auc_xlstm

Activation Updates:
    - Replaced GELU/LeakyReLU activations with standard ReLU (`nn.ReLU`).
    - Standardized traditional Sigmoid gating (`torch.sigmoid`) for output gates
      and classification activation probabilities.
"""

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ----------------------------------------------------------------------
# 1. Load Data
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"  # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int64")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# PVC descriptors stabilization via signed-log (arcsinh)
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Train / Independent-test Split (80/20, Stratified)
# ----------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# ----------------------------------------------------------------------
# 3. Feature Scaling (Fit ONLY on Train)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype("float32")
X_test = scaler.transform(X_test).astype("float32")

n_features = X_train.shape[1]

# Convert to PyTorch Tensors
X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.long)
X_test_t  = torch.tensor(X_test, dtype=torch.float32)
y_test_t  = torch.tensor(y_test, dtype=torch.long)

train_dataset = TensorDataset(X_train_t, y_train_t)
test_dataset  = TensorDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_dataset, batch_size=256, shuffle=False)

# ----------------------------------------------------------------------
# 4. xLSTM Architecture Components (Updated with ReLU & Sigmoid)
# ----------------------------------------------------------------------
class sLSTMCell(nn.Module):
    """
    sLSTM cell with exponential gating, ReLU cell updates, and Sigmoid output gating.
    """
    def __init__(self, hidden_dim):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.w_i = nn.Linear(hidden_dim, hidden_dim)
        self.w_f = nn.Linear(hidden_dim, hidden_dim)
        self.w_o = nn.Linear(hidden_dim, hidden_dim)
        self.w_z = nn.Linear(hidden_dim, hidden_dim)

        self.r_i = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.r_f = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.r_o = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.r_z = nn.Linear(hidden_dim, hidden_dim, bias=False)

    def forward(self, x, state=None):
        batch_size, seq_len, _ = x.shape
        if state is None:
            h = torch.zeros(batch_size, self.hidden_dim, device=x.device)
            c = torch.zeros(batch_size, self.hidden_dim, device=x.device)
            n = torch.zeros(batch_size, self.hidden_dim, device=x.device)
            m = torch.zeros(batch_size, self.hidden_dim, device=x.device)
        else:
            h, c, n, m = state

        outputs = []
        for t in range(seq_len):
            x_t = x[:, t, :]

            # Gating projections
            i_tilde = self.w_i(x_t) + self.r_i(h)
            f_tilde = self.w_f(x_t) + self.r_f(h)
            o_tilde = self.w_o(x_t) + self.r_o(h)

            # ReLU cell candidate modulation
            z_t     = F.relu(self.w_z(x_t) + self.r_z(h))

            # Stabilized exponential gates & Sigmoid output gate
            m_next = torch.maximum(f_tilde + m, i_tilde)
            i_gate = torch.exp(i_tilde - m_next)
            f_gate = torch.exp(f_tilde + m - m_next)
            o_gate = torch.sigmoid(o_tilde)  # Standard Sigmoid Activation

            c = f_gate * c + i_gate * z_t
            n = f_gate * n + i_gate
            m = m_next

            # ReLU output state activation normalized by state tracking
            h = o_gate * F.relu(c / torch.clamp(n, min=1e-6))
            outputs.append(h.unsqueeze(1))

        outputs = torch.cat(outputs, dim=1)
        return outputs, (h, c, n, m)


class mLSTMCell(nn.Module):
    """
    mLSTM cell with matrix memory key-value retrieval and Sigmoid gating.
    """
    def __init__(self, hidden_dim, num_heads=4):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = hidden_dim // num_heads

        self.q_proj = nn.Linear(hidden_dim, hidden_dim)
        self.k_proj = nn.Linear(hidden_dim, hidden_dim)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)

        self.i_gate = nn.Linear(hidden_dim, num_heads)
        self.f_gate = nn.Linear(hidden_dim, num_heads)
        self.o_gate = nn.Linear(hidden_dim, hidden_dim)

        self.out_proj = nn.Linear(hidden_dim, hidden_dim)

    def forward(self, x):
        batch_size, seq_len, _ = x.shape

        Q = self.q_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim)
        K = self.k_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim) / np.sqrt(self.head_dim)
        V = self.v_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim)

        i = torch.exp(self.i_gate(x))                  # Input gate
        f = torch.sigmoid(self.f_gate(x))              # Forget gate (Sigmoid)
        o = torch.sigmoid(self.o_gate(x))              # Output gate (Sigmoid)

        C = torch.zeros(batch_size, self.num_heads, self.head_dim, self.head_dim, device=x.device)
        outputs = []

        for t in range(seq_len):
            q_t = Q[:, t]
            k_t = K[:, t]
            v_t = V[:, t]
            i_t = i[:, t].unsqueeze(-1).unsqueeze(-1)
            f_t = f[:, t].unsqueeze(-1).unsqueeze(-1)

            kv_outer = torch.matmul(k_t.unsqueeze(-1), v_t.unsqueeze(-2))
            C = f_t * C + i_t * kv_outer

            h_t = torch.matmul(q_t.unsqueeze(-2), C).squeeze(-2)
            h_flat = h_t.view(batch_size, self.hidden_dim)
            outputs.append(h_flat.unsqueeze(1))

        out = torch.cat(outputs, dim=1) * o
        return self.out_proj(out)


class xLSTMBlock(nn.Module):
    def __init__(self, hidden_dim, num_heads=4):
        super().__init__()
        self.ln1 = nn.LayerNorm(hidden_dim)
        self.mlstm = mLSTMCell(hidden_dim, num_heads=num_heads)
        self.ln2 = nn.LayerNorm(hidden_dim)
        self.slstm = sLSTMCell(hidden_dim)

        # Feed-forward block updated to standard ReLU activation
        self.ffn = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim * 2),
            nn.ReLU(),                                  # Replaced GELU with ReLU
            nn.Dropout(0.2),
            nn.Linear(hidden_dim * 2, hidden_dim)
        )

    def forward(self, x):
        # mLSTM residual branch
        x = x + self.mlstm(self.ln1(x))
        # sLSTM residual branch
        s_out, _ = self.slstm(self.ln2(x))
        x = x + s_out
        # Feed-forward residual branch
        x = x + self.ffn(x)
        return x


class xLSTMClassifier(nn.Module):
    def __init__(self, input_dim, seq_len=16, hidden_dim=128, num_classes=2):
        super().__init__()
        self.seq_len = seq_len
        self.chunk_dim = input_dim // seq_len
        self.remainder = input_dim % seq_len

        # Token projection
        self.input_proj = nn.Linear(self.chunk_dim + (1 if self.remainder > 0 else 0), hidden_dim)

        # Stacked xLSTM Blocks
        self.xlstm1 = xLSTMBlock(hidden_dim, num_heads=4)
        self.xlstm2 = xLSTMBlock(hidden_dim, num_heads=4)

        # Classification Head updated with ReLU activation
        self.head = nn.Sequential(
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, 64),
            nn.ReLU(),                                  # Replaced LeakyReLU/GELU with ReLU
            nn.Dropout(0.3),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        batch_size = x.size(0)

        # Sequence chunking/padding
        if self.remainder > 0:
            pad_size = self.seq_len - self.remainder
            x_padded = F.pad(x, (0, pad_size))
        else:
            x_padded = x

        chunks = x_padded.view(batch_size, self.seq_len, -1)

        # Project chunks into sequence embeddings
        tokens = self.input_proj(chunks)

        # Pass through xLSTM layers
        x_rec = self.xlstm1(tokens)
        x_rec = self.xlstm2(x_rec)

        # Temporal Pooling (Mean + Max)
        pooled = torch.mean(x_rec, dim=1) + torch.max(x_rec, dim=1)[0]
        logits = self.head(pooled)
        return logits


# Instantiation
model = xLSTMClassifier(input_dim=n_features, seq_len=16, hidden_dim=128).to(device)
print(model)

# ----------------------------------------------------------------------
# 5. Model Training Setup
# ----------------------------------------------------------------------
criterion = nn.CrossEntropyLoss(label_smoothing=0.05)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100, eta_min=1e-5)

# Training Loop with Early Stopping
best_loss = float("inf")
patience, counter = 15, 0
best_model_weights = None

epochs = 100
print("\nStarting Training...")

for epoch in range(1, epochs + 1):
    model.train()
    train_loss = 0.0
    for batch_X, batch_y in train_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)

        optimizer.zero_grad()
        logits = model(batch_X)
        loss = criterion(logits, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        train_loss += loss.item() * batch_X.size(0)

    train_loss /= len(train_loader.dataset)
    scheduler.step()

    # Early stopping check
    if train_loss < best_loss:
        best_loss = train_loss
        counter = 0
        best_model_weights = model.state_dict().copy()
    else:
        counter += 1
        if counter >= patience:
            print(f"Early stopping triggered at epoch {epoch}")
            break

    if epoch % 10 == 0 or epoch == 1:
        print(f"Epoch {epoch:03d}/{epochs} | Loss: {train_loss:.4f} | LR: {scheduler.get_last_lr()[0]:.6f}")

# Restore best model weights
if best_model_weights is not None:
    model.load_state_dict(best_model_weights)

# ----------------------------------------------------------------------
# 6. Independent Test Evaluation
# ----------------------------------------------------------------------
model.eval()
test_preds = []
test_probs = []

with torch.no_grad():
    for batch_X, _ in test_loader:
        batch_X = batch_X.to(device)
        logits = model(batch_X)
        probs = F.softmax(logits, dim=1)

        preds = torch.argmax(probs, dim=1)

        test_preds.extend(preds.cpu().numpy())
        test_probs.extend(probs[:, 1].cpu().numpy())

y_pred = np.array(test_preds)
y_pred_prob = np.array(test_probs)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = recall_score(y_test, y_pred)               # = TPR / recall
specificity = tn / (tn + fp)
precision   = precision_score(y_test, y_pred)
f1          = f1_score(y_test, y_pred)
mcc         = matthews_corrcoef(y_test, y_pred)
auc_score   = roc_auc_score(y_test, y_pred_prob)

print("\n============= Independent Test Results (xLSTM Network) =============")
print(f"Accuracy    : {accuracy*100:.2f}%")
print(f"Sensitivity : {sensitivity*100:.2f}%")
print(f"Specificity : {specificity*100:.2f}%")
print(f"Precision   : {precision*100:.2f}%")
print(f"F1-score    : {f1*100:.2f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==============================================================================")

# ----------------------------------------------------------------------
# 7. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_xlstm, tpr_xlstm, thresholds_xlstm = roc_curve(y_test, y_pred_prob)
roc_auc_xlstm = auc(fpr_xlstm, tpr_xlstm)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_xlstm,
    tpr_xlstm,
    color="darkorange",
    lw=2,
    label=f"xLSTM Network (AUC = {roc_auc_xlstm:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - xLSTM Network (Independent Test)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_xLSTM_Independent.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 8. Save Metrics to CSV
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "xLSTM_Network",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_xlstm,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("xLSTM_Independent_Results.csv", index=False)
print("\nSaved: xLSTM_Independent_Results.csv")
print("Saved: ROC_xLSTM_Independent.png")

# ----------------------------------------------------------------------
# 9. Save ROC Values (npz format for model comparison)
# ----------------------------------------------------------------------
np.savez(
    "roc_values_xlstm.npz",
    fpr_xlstm=fpr_xlstm,
    tpr_xlstm=tpr_xlstm,
    roc_auc_xlstm=roc_auc_xlstm,
)
print("Saved: roc_values_xlstm.npz")



import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, roc_auc

plt.figure(figsize=(7, 7))

# Model 1: Siamese Network
plt.plot(
    fpr_siamese,
    tpr_siamese,
    color="teal",
    lw=2.5,
    label=f"Siamese Contrastive (AUC = {roc_auc_siamese:.4f})"
)

# Model 2: xLSTM Network
plt.plot(
    fpr_xlstm,
    tpr_xlstm,
    color="darkorange",
    lw=2.5,
    label=f"xLSTM Network (AUC = {roc_auc_xlstm:.4f})"
)
# ==========================================================
# GRID
# ==========================================================

plt.grid(
    True,
    linestyle='--',
    alpha=0.4
)
# Random baseline
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--", label="Baseline")

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Comparative ROC Curves-Independent Test (Gylcometabolic Protein)")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("Merged_ROC_Comparison.png", dpi=300)
plt.show()

# ==========================================================

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import auc
# ==========================================================
# FULL HD FIGURE
# ==========================================================

plt.figure(
    figsize=(8,8),
    dpi=300
)
plt.plot(
    fpr_cnntransformer,
    tpr_cnntransformer,
    color="darkorange",
    lw=2,
    label=f"CNN-Transformer (AUC = {roc_auc_cnntransformer:.4f})",
)

plt.plot(
    fpr_xlstm,
    tpr_xlstm,
    color="yellow",
    lw=2,
    label=f"xLSTM  (AUC = {roc_auc_xlstm:.4f})",
)
plt.plot(
    fpr_mamba,
    tpr_mamba,
    color="purple",
    lw=2,
    label=f"Mamba-2 (AUC = {roc_auc_mamba:.4f})",
)
plt.plot(
    fpr_siamese,
    tpr_siamese,
    color="teal",
    lw=2,
    label=f"Siamese Contrastive (AUC = {roc_auc_siamese:.4f})",
)
plt.plot(
    fpr_capsule,
    tpr_capsule,
    color="crimson",
    lw=2,
    label=f"Capsule Hybrid Network (AUC = {roc_auc_capsule:.4f})",
)
plt.plot(
    fpr_kan,
    tpr_kan,
    color="green",
    lw=2,
    label=f"Kolmogorov–Arnold Network (AUC = {roc_auc_kan:.4f})",
)

# ==========================================================
# LABELS
# ==========================================================

plt.xlabel(
    'False Positive Rate',
    fontsize=12,
    fontweight='bold'
)

plt.ylabel(
    'True Positive Rate',
    fontsize=12,
    fontweight='bold'
)

plt.title(
    'Comparative ROC Curves-Independent Test of ESM-2 (Gylcometabolic Protein)',
    fontsize=12,
    fontweight='bold'
)

# ==========================================================
# TICKS
# ==========================================================

plt.xticks(fontsize=14)

plt.yticks(fontsize=14)

# ==========================================================
# GRID
# ==========================================================

plt.grid(
    True,
    linestyle='--',
    alpha=0.4
)

# ==========================================================
# LEGEND
# ==========================================================

plt.legend(
    loc='lower right',
    fontsize=12,
    frameon=True
)

# ==========================================================
# SAVE FULL HD IMAGE
# ==========================================================

plt.savefig(
    "Merged_ROC_Curves_FullHD.png",
    dpi=600,
    bbox_inches='tight'
)

# ==========================================================
# SAVE PDF
# ==========================================================

plt.savefig(
    "Merged_ROC_Curves_FullHD.pdf",
    bbox_inches='tight'
)

# ==========================================================
# SHOW FIGURE
# ==========================================================

plt.show()