# -*- coding: utf-8 -*-
"""ESM-2-GylcometabolicProteinSelf-Consistency_test27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KWTCqMFD_7mE52ryWJCd6iAEQbiWeeA
"""

"""
CNN-Transformer Model - Pure Self-Consistency (100% Dataset Training)
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Strategy: Pure Self-Consistency Evaluation (100% Dataset for Training & Testing)
          No independent test split, No K-Fold Cross Validation.
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_cnntransformer, tpr_cnntransformer, roc_auc_cnntransformer
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load Data (100% used for Self-Consistency)
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

X = df.drop(columns=["Label"]).values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# arcsinh scaling (signed log) to handle high dynamic range PVC features
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Feature Scaling & Reshaping (Fit on entire dataset)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype("float32")

# Reshape for Conv1D: (samples, timesteps, channels)
X_scaled = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1], 1)
n_features = X_scaled.shape[1]

# ----------------------------------------------------------------------
# 3. Custom Layers & Architectures
# ----------------------------------------------------------------------
class PositionalEmbedding(layers.Layer):
    """Adds learnable positional embeddings across the feature dimension."""
    def __init__(self, sequence_length, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.sequence_length = sequence_length
        self.output_dim = output_dim
        self.pos_emb = layers.Embedding(input_dim=sequence_length, output_dim=output_dim)

    def call(self, inputs):
        positions = tf.range(start=0, limit=self.sequence_length, delta=1)
        return inputs + self.pos_emb(positions)


def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    x = layers.LayerNormalization(epsilon=1e-6)(inputs)
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(x, x)
    x = layers.Dropout(dropout)(x)
    res = x + inputs

    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(x)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=res.shape[-1], kernel_size=1)(x)
    return x + res


def build_cnn_transformer(input_len):
    inputs = layers.Input(shape=(input_len, 1))

    # Conv1D Feature Extraction Blocks
    x = layers.Conv1D(64, kernel_size=7, strides=2, padding="same")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    res = x
    x = layers.Conv1D(64, kernel_size=5, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.Conv1D(64, kernel_size=5, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.add([x, res])
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    x = layers.Conv1D(128, kernel_size=3, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    seq_len = x.shape[1]
    embed_dim = x.shape[2]

    # Positional Embedding + Multi-layer Transformer Stack
    x = PositionalEmbedding(sequence_length=seq_len, output_dim=embed_dim)(x)

    for _ in range(3):
        x = transformer_encoder(x, head_size=64, num_heads=8, ff_dim=256, dropout=0.1)

    # Pooling
    avg_pool = layers.GlobalAveragePooling1D()(x)
    max_pool = layers.GlobalMaxPooling1D()(x)
    pooled = layers.concatenate([avg_pool, max_pool])

    # Classifier
    x = layers.Dense(256, activation="relu")(pooled)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.2)(x)

    x = layers.Dense(128, activation="relu")(x)
    x = layers.BatchNormalization()(x)

    outputs = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inputs, outputs, name="CNN_Transformer_SelfConsistency")

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return model


# Build CNN-Transformer
cnn_transformer = build_cnn_transformer(n_features)
cnn_transformer.summary()

# ----------------------------------------------------------------------
# 4. Train Model on 100% of Dataset (Self-Consistency)
# ----------------------------------------------------------------------
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="loss", factor=0.5, patience=5, min_lr=1e-6
)

print("\nStarting Training on 100% Dataset for Self-Consistency...")
history = cnn_transformer.fit(
    X_scaled, y,
    batch_size=32,
    epochs=100,
    callbacks=[reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 5. Evaluate Self-Consistency
# ----------------------------------------------------------------------
y_pred_prob = cnn_transformer.predict(X_scaled, batch_size=256).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()

accuracy    = accuracy_score(y, y_pred)
sensitivity = recall_score(y, y_pred)
specificity = tn / (tn + fp)
precision   = precision_score(y, y_pred)
f1          = f1_score(y, y_pred)
mcc         = matthews_corrcoef(y, y_pred)
auc_score   = roc_auc_score(y, y_pred_prob)

print("\n================ Self-Consistency Results (100% Training) ================")
print(f"Accuracy    : {accuracy*100:.2f}%")
print(f"Sensitivity : {sensitivity*100:.2f}%")
print(f"Specificity : {specificity*100:.2f}%")
print(f"Precision   : {precision*100:.2f}%")
print(f"F1-score    : {f1*100:.2f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==========================================================================")

# ----------------------------------------------------------------------
# 6. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_cnntransformer, tpr_cnntransformer, thresholds_cnntransformer = roc_curve(y, y_pred_prob)
roc_auc_cnntransformer = auc(fpr_cnntransformer, tpr_cnntransformer)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_cnntransformer,
    tpr_cnntransformer,
    color="darkorange",
    lw=2,
    label=f"CNN-Transformer Self-Consistency (AUC = {roc_auc_cnntransformer:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - CNN-Transformer (Self-Consistency)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_CNN_Transformer_SelfConsistency.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 7. Save Metrics to CSV and ROC variables to NPZ
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "CNN_Transformer_SelfConsistency",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_cnntransformer,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("CNN_Transformer_SelfConsistency_Results.csv", index=False)

np.savez(
    "roc_values_cnntransformer.npz",
    fpr_cnntransformer=fpr_cnntransformer,
    tpr_cnntransformer=tpr_cnntransformer,
    roc_auc_cnntransformer=roc_auc_cnntransformer,
)

print("\nSaved: CNN_Transformer_SelfConsistency_Results.csv")
print("Saved: ROC_CNN_Transformer_SelfConsistency.png")
print("Saved: roc_values_cnntransformer.npz")



"""
KAN (Kolmogorov-Arnold Network) - Pure Self-Consistency (100% Dataset Training)
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Strategy: Pure Self-Consistency Evaluation (100% Dataset for Training & Evaluation)
          No independent test split, No K-Fold Cross Validation.
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_kan, tpr_kan, roc_auc_kan

Enhancements for High Self-Consistency Accuracy:
    1. Arcsinh feature transformation for extreme dynamic range stability.
    2. Hybrid ChebyKAN + Residual Dense bottleneck architecture.
    3. Multi-degree Chebyshev polynomial basis expansion (degree=5).
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load Data (100% used for Self-Consistency)
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

X = df.drop(columns=["Label"]).values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# arcsinh scaling (signed log) handles high dynamic range PVC features
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Feature Scaling (Fit on entire dataset)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype("float32")
n_features = X_scaled.shape[1]

# ----------------------------------------------------------------------
# 3. Enhanced ChebyKAN Layer
# ----------------------------------------------------------------------
class ChebyKANLayer(layers.Layer):
    """
    Kolmogorov-Arnold layer via Chebyshev polynomials.
    """
    def __init__(self, out_features, degree=5, **kwargs):
        super().__init__(**kwargs)
        self.out_features = out_features
        self.degree = degree

    def build(self, input_shape):
        in_features = int(input_shape[-1])
        self.in_features = in_features

        self.coeffs = self.add_weight(
            name="cheby_coeffs",
            shape=(in_features, self.out_features, self.degree + 1),
            initializer=tf.keras.initializers.RandomNormal(
                mean=0.0, stddev=1.0 / np.sqrt(in_features * (self.degree + 1))
            ),
            trainable=True,
        )
        self.bias = self.add_weight(
            name="bias",
            shape=(self.out_features,),
            initializer="zeros",
            trainable=True,
        )

    def call(self, x):
        # Normalization to Chebyshev domain [-1, 1]
        x = tf.tanh(x)

        # Chebyshev basis expansion
        basis = [tf.ones_like(x), x]
        for _ in range(2, self.degree + 1):
            basis.append(2.0 * x * basis[-1] - basis[-2])
        basis = tf.stack(basis, axis=-1)

        # Tensor dot product combining learned univariate edge functions
        out = tf.einsum("bid,iod->bo", basis, self.coeffs)
        return out + self.bias

    def get_config(self):
        config = super().get_config()
        config.update({"out_features": self.out_features, "degree": self.degree})
        return config


# ----------------------------------------------------------------------
# 4. Build KAN Self-Consistency Architecture
# ----------------------------------------------------------------------
def build_kan_self_consistency(input_dim, degree=5):
    inputs = layers.Input(shape=(input_dim,))

    # Initial Feature Bottleneck Projection
    x_proj = layers.Dense(512, activation="relu")(inputs)
    x_proj = layers.BatchNormalization()(x_proj)

    # First KAN Layer
    x = ChebyKANLayer(256, degree=degree)(x_proj)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    # Second KAN Layer with Residual Connection
    res = layers.Dense(256)(x_proj)
    x = ChebyKANLayer(256, degree=degree)(x)
    x = layers.add([x, res])
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    # Third KAN Layer
    x = ChebyKANLayer(128, degree=degree)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    # Classification Output Head
    x = layers.Dense(64, activation="relu")(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    kan = models.Model(inputs, outputs, name="KAN_SelfConsistency")

    kan.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return kan


kan = build_kan_self_consistency(n_features, degree=5)
kan.summary()

# ----------------------------------------------------------------------
# 5. Train Model on 100% of Dataset (Self-Consistency)
# ----------------------------------------------------------------------
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="loss", factor=0.5, patience=5, min_lr=1e-6
)

print("\nStarting KAN Training on 100% Dataset for Self-Consistency...")
history = kan.fit(
    X_scaled, y,
    batch_size=32,
    epochs=100,
    callbacks=[reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 6. Evaluate Self-Consistency
# ----------------------------------------------------------------------
y_pred_prob = kan.predict(X_scaled, batch_size=256).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()

accuracy    = accuracy_score(y, y_pred)
sensitivity = recall_score(y, y_pred)
specificity = tn / (tn + fp)
precision   = precision_score(y, y_pred)
f1          = f1_score(y, y_pred)
mcc         = matthews_corrcoef(y, y_pred)
auc_score   = roc_auc_score(y, y_pred_prob)

print("\n================ Self-Consistency Results (KAN - 100% Training) ================")
print(f"Accuracy    : {accuracy*100:.4f}%")
print(f"Sensitivity : {sensitivity*100:.4f}%")
print(f"Specificity : {specificity*100:.4f}%")
print(f"Precision   : {precision*100:.4f}%")
print(f"F1-score    : {f1*100:.4f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==================================================================================")

# ----------------------------------------------------------------------
# 7. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_kan, tpr_kan, thresholds_kan = roc_curve(y, y_pred_prob)
roc_auc_kan = auc(fpr_kan, tpr_kan)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_kan,
    tpr_kan,
    color="green",
    lw=2,
    label=f"KAN Self-Consistency (AUC = {roc_auc_kan:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - KAN (Self-Consistency)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_KAN_SelfConsistency.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 8. Save Metrics to CSV and ROC variables to NPZ
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "KAN_SelfConsistency",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_kan,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("KAN_SelfConsistency_Results.csv", index=False)

np.savez(
    "roc_values_kan.npz",
    fpr_kan=fpr_kan,
    tpr_kan=tpr_kan,
    roc_auc_kan=roc_auc_kan,
)

print("\nSaved: KAN_SelfConsistency_Results.csv")
print("Saved: ROC_KAN_SelfConsistency.png")
print("Saved: roc_values_kan.npz")



"""
Capsule Hybrid Network - High Capacity Pure Self-Consistency (100% Dataset Training)
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Strategy: Pure Self-Consistency Evaluation (100% Dataset for Training & Evaluation)
          No independent test split, No K-Fold Cross Validation.
Batch   : 32
Epochs  : 100
Outputs : Accuracy (~99%+), Sensitivity, Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_capsule, tpr_capsule, roc_auc_capsule

Key Enhancements for 99%+ Accuracy:
    1. Deep Residual Multi-scale Conv1D Feature Extraction.
    2. High-Capacity Primary Capsule Layer (64 channels, 16 dimensions).
    3. Expanded Digit/Class Capsules (32 dimensions).
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load Data (100% used for Self-Consistency)
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# Arcsinh scaling (signed log) to stabilize extreme dynamic ranges
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Feature Scaling & Reshaping (Fit on entire dataset)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype("float32")

# Reshape to (samples, timesteps, channels) for Conv1D processing
X_scaled = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1], 1)
n_features = X_scaled.shape[1]

# ----------------------------------------------------------------------
# 3. Enhanced Capsule Network Building Blocks
# ----------------------------------------------------------------------
def squash(vectors, axis=-1, epsilon=1e-7):
    """Squashing activation function bounds capsule vector length between [0, 1)."""
    s_squared_norm = tf.reduce_sum(tf.square(vectors), axis=axis, keepdims=True)
    scale = s_squared_norm / (1.0 + s_squared_norm) / tf.sqrt(s_squared_norm + epsilon)
    return scale * vectors


class PrimaryCapsule(layers.Layer):
    """Expanded Conv1D feature transformation into rich vector capsules."""
    def __init__(self, num_channels, dim_capsule, kernel_size=3, strides=1, **kwargs):
        super().__init__(**kwargs)
        self.num_channels = num_channels
        self.dim_capsule = dim_capsule
        self.kernel_size = kernel_size
        self.strides = strides
        self.conv = layers.Conv1D(
            filters=num_channels * dim_capsule,
            kernel_size=kernel_size,
            strides=strides,
            padding="same",
            activation="relu",
        )

    def call(self, inputs):
        x = self.conv(inputs)
        t = tf.shape(x)[1]
        x = tf.reshape(x, (-1, t * self.num_channels, self.dim_capsule))
        return squash(x)

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_channels": self.num_channels,
            "dim_capsule": self.dim_capsule,
            "kernel_size": self.kernel_size,
            "strides": self.strides,
        })
        return config


class CapsuleRoutingLayer(layers.Layer):
    """Class Capsule Layer with dynamic routing-by-agreement."""
    def __init__(self, num_capsules, dim_capsule, routings=3, **kwargs):
        super().__init__(**kwargs)
        self.num_capsules = num_capsules
        self.dim_capsule = dim_capsule
        self.routings = routings

    def build(self, input_shape):
        self.input_num_capsules = int(input_shape[1])
        self.input_dim_capsule = int(input_shape[2])
        self.W = self.add_weight(
            shape=(self.input_num_capsules, self.num_capsules,
                   self.dim_capsule, self.input_dim_capsule),
            initializer="glorot_uniform",
            name="routing_weights",
            trainable=True,
        )

    def call(self, inputs):
        u_hat = tf.einsum("bic,ikdc->bikd", inputs, self.W)
        u_hat_stopped = tf.stop_gradient(u_hat)

        batch_size = tf.shape(inputs)[0]
        b = tf.zeros((batch_size, self.input_num_capsules, self.num_capsules))

        v = None
        for r in range(self.routings):
            c = tf.nn.softmax(b, axis=2)
            use_hat = u_hat if r == self.routings - 1 else u_hat_stopped
            s = tf.einsum("bik,bikd->bkd", c, use_hat)
            v = squash(s)
            if r < self.routings - 1:
                b += tf.einsum("bkd,bikd->bik", v, use_hat)
        return v

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_capsules": self.num_capsules,
            "dim_capsule": self.dim_capsule,
            "routings": self.routings,
        })
        return config


class CapsuleLength(layers.Layer):
    """Computes vector length for each output capsule (presence probability)."""
    def call(self, inputs):
        return tf.sqrt(tf.reduce_sum(tf.square(inputs), axis=-1) + 1e-7)


# ----------------------------------------------------------------------
# 4. Build High-Capacity Capsule Hybrid Network Architecture
# ----------------------------------------------------------------------
def build_high_capacity_capsule_hybrid(input_len):
    inputs = layers.Input(shape=(input_len, 1))

    # Stage 1: Conv Block with Large Kernel
    x1 = layers.Conv1D(128, kernel_size=9, padding="same", activation="relu")(inputs)
    x1 = layers.BatchNormalization()(x1)

    # Stage 2: Residual Block with Medium Kernel
    x2 = layers.Conv1D(256, kernel_size=5, padding="same", activation="relu")(x1)
    x2 = layers.BatchNormalization()(x2)
    x2 = layers.MaxPooling1D(pool_size=2)(x2)

    # Stage 3: Deep Feature Projection Block
    x3 = layers.Conv1D(256, kernel_size=3, padding="same", activation="relu")(x2)
    x3 = layers.BatchNormalization()(x3)
    x3 = layers.MaxPooling1D(pool_size=2)(x3)

    # Capsule Back-end with Enhanced Channel & Vector Dimensions
    x_caps = PrimaryCapsule(num_channels=64, dim_capsule=16, kernel_size=3, strides=2)(x3)
    x_routing = CapsuleRoutingLayer(num_capsules=2, dim_capsule=32, routings=3)(x_caps)
    lengths = CapsuleLength()(x_routing)
    outputs = layers.Softmax(name="class_probabilities")(lengths)

    capsule_hybrid = models.Model(inputs, outputs, name="High_Capacity_Capsule_Hybrid")
    capsule_hybrid.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return capsule_hybrid


capsule_hybrid = build_high_capacity_capsule_hybrid(n_features)
capsule_hybrid.summary()

# ----------------------------------------------------------------------
# 5. Train Model on 100% of Dataset (Self-Consistency)
# ----------------------------------------------------------------------
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="loss", factor=0.5, patience=4, min_lr=1e-6
)

print("\nStarting Optimized Capsule Hybrid Training on 100% Dataset for High Self-Consistency...")
history = capsule_hybrid.fit(
    X_scaled, y,
    batch_size=32,
    epochs=100,
    callbacks=[reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 6. Evaluate Self-Consistency
# ----------------------------------------------------------------------
y_prob_both = capsule_hybrid.predict(X_scaled, batch_size=256)
y_pred_prob = y_prob_both[:, 1]
y_pred = np.argmax(y_prob_both, axis=1)

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()

accuracy    = accuracy_score(y, y_pred)
sensitivity = recall_score(y, y_pred)
specificity = tn / (tn + fp)
precision   = precision_score(y, y_pred)
f1          = f1_score(y, y_pred)
mcc         = matthews_corrcoef(y, y_pred)
auc_score   = roc_auc_score(y, y_pred_prob)

print("\n================ Self-Consistency Results (Capsule Hybrid - 100% Training) ================")
print(f"Accuracy    : {accuracy*100:.4f}%")
print(f"Sensitivity : {sensitivity*100:.4f}%")
print(f"Specificity : {specificity*100:.4f}%")
print(f"Precision   : {precision*100:.4f}%")
print(f"F1-score    : {f1*100:.4f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==========================================================================================")

# ----------------------------------------------------------------------
# 7. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_capsule, tpr_capsule, thresholds_capsule = roc_curve(y, y_pred_prob)
roc_auc_capsule = auc(fpr_capsule, tpr_capsule)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_capsule,
    tpr_capsule,
    color="crimson",
    lw=2,
    label=f"Capsule Hybrid Self-Consistency (AUC = {roc_auc_capsule:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Capsule Hybrid Network (Self-Consistency)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_Capsule_Hybrid_SelfConsistency.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 8. Save Metrics to CSV and ROC variables to NPZ
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "Capsule_Hybrid_SelfConsistency",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_capsule,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("Capsule_Hybrid_SelfConsistency_Results.csv", index=False)

np.savez(
    "roc_values_capsule.npz",
    fpr_capsule=fpr_capsule,
    tpr_capsule=tpr_capsule,
    roc_auc_capsule=roc_auc_capsule,
)

print("\nSaved: Capsule_Hybrid_SelfConsistency_Results.csv")
print("Saved: ROC_Capsule_Hybrid_SelfConsistency.png")
print("Saved: roc_values_capsule.npz")



"""
Siamese Contrastive Network - Pure Self-Consistency (100% Dataset Training)
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Strategy: Pure Self-Consistency Evaluation (100% Dataset for Training & Evaluation)
          No independent test split, No K-Fold Cross Validation.
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_siamese, tpr_siamese, roc_auc_siamese

How it works:
    1. A shared "twin" encoder network maps every sample into an embedding space.
    2. Trained on PAIRS generated from 100% of the dataset with contrastive loss.
    3. Class prototypes (centroids for Class 0 and Class 1) are computed from
       embeddings across the entire dataset.
    4. Distance to prototypes determines self-consistency classification.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
rng = np.random.default_rng(SEED)

# ----------------------------------------------------------------------
# 1. Load Data (100% used for Self-Consistency)
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# arcsinh scaling (signed log) handles high dynamic range PVC features
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Feature Scaling (Fit on entire dataset)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype("float32")
n_features = X_scaled.shape[1]

# ----------------------------------------------------------------------
# 3. Pair Generation (Built from 100% of the dataset)
# ----------------------------------------------------------------------
def make_pairs(X, y, pairs_per_sample=3, rng=rng):
    """Generates positive and negative pair samples for contrastive learning."""
    class0_idx = np.where(y == 0)[0]
    class1_idx = np.where(y == 1)[0]
    idx_by_class = {0: class0_idx, 1: class1_idx}

    left, right, labels = [], [], []
    n = len(y)
    for i in range(n):
        cls = y[i]
        same_pool = idx_by_class[cls]
        diff_pool = idx_by_class[1 - cls]

        # Positive (similar) pairs
        for _ in range(pairs_per_sample):
            j = rng.choice(same_pool)
            left.append(i); right.append(j); labels.append(1)

        # Negative (dissimilar) pairs
        for _ in range(pairs_per_sample):
            j = rng.choice(diff_pool)
            left.append(i); right.append(j); labels.append(0)

    left, right, labels = np.array(left), np.array(right), np.array(labels)
    perm = rng.permutation(len(labels))
    left, right, labels = left[perm], right[perm], labels[perm]
    return X[left], X[right], labels.astype("float32")


X_left, X_right, pair_labels = make_pairs(X_scaled, y, pairs_per_sample=3)
print(f"Generated dataset pairs: {X_left.shape[0]} "
      f"(similar={int(pair_labels.sum())}, dissimilar={int((1-pair_labels).sum())})")

# ----------------------------------------------------------------------
# 4. Shared Twin Encoder Architecture
# ----------------------------------------------------------------------
EMBED_DIM = 128

def build_encoder(input_dim, embed_dim=EMBED_DIM):
    inputs = layers.Input(shape=(input_dim,))

    x = layers.Dense(1024, activation="relu")(inputs)
    x = layers.BatchNormalization()(x)

    x = layers.Dense(512, activation="relu")(x)
    x = layers.BatchNormalization()(x)

    x = layers.Dense(256, activation="relu")(x)
    x = layers.BatchNormalization()(x)

    embeddings = layers.Dense(embed_dim, activation=None, name="embedding")(x)
    # L2-normalize embeddings -> distances remain bounded
    embeddings = layers.Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(embeddings)
    return models.Model(inputs, embeddings, name="Twin_Encoder")


encoder = build_encoder(n_features)
encoder.summary()

# ----------------------------------------------------------------------
# 5. Distance and Contrastive Loss Definitions
# ----------------------------------------------------------------------
def euclidean_distance(vectors):
    x, y_ = vectors
    sum_sq = tf.reduce_sum(tf.square(x - y_), axis=1, keepdims=True)
    return tf.sqrt(tf.maximum(sum_sq, 1e-9))


def contrastive_loss(margin=1.0):
    def loss(y_true, y_pred):
        y_true = tf.cast(y_true, y_pred.dtype)
        square_pred = tf.square(y_pred)
        margin_square = tf.square(tf.maximum(margin - y_pred, 0.0))
        return tf.reduce_mean(y_true * square_pred + (1.0 - y_true) * margin_square)
    return loss


input_a = layers.Input(shape=(n_features,), name="input_a")
input_b = layers.Input(shape=(n_features,), name="input_b")

embed_a = encoder(input_a)
embed_b = encoder(input_b)

distance = layers.Lambda(euclidean_distance, name="euclidean_distance")([embed_a, embed_b])

siamese_contrastive = models.Model(inputs=[input_a, input_b], outputs=distance,
                                    name="Siamese_Contrastive_Network")
siamese_contrastive.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss=contrastive_loss(margin=1.0),
)
siamese_contrastive.summary()

# ----------------------------------------------------------------------
# 6. Train Siamese Network on 100% Data (Self-Consistency)
# ----------------------------------------------------------------------
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="loss", factor=0.5, patience=5, min_lr=1e-6
)

print("\nStarting Siamese Training on 100% Dataset for Self-Consistency...")
history = siamese_contrastive.fit(
    [X_left, X_right], pair_labels,
    batch_size=32,
    epochs=100,
    callbacks=[reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 7. Build Class Prototypes & Evaluate Self-Consistency
# ----------------------------------------------------------------------
all_embeddings = encoder.predict(X_scaled, batch_size=256)

prototype_0 = all_embeddings[y == 0].mean(axis=0)
prototype_1 = all_embeddings[y == 1].mean(axis=0)

dist_to_0 = np.linalg.norm(all_embeddings - prototype_0, axis=1)
dist_to_1 = np.linalg.norm(all_embeddings - prototype_1, axis=1)

y_pred = (dist_to_1 < dist_to_0).astype(int)            # Closer prototype wins
y_pred_prob = tf.sigmoid((dist_to_0 - dist_to_1) * 3.0).numpy() # Probability mapping

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()

accuracy    = accuracy_score(y, y_pred)
sensitivity = recall_score(y, y_pred)
specificity = tn / (tn + fp)
precision   = precision_score(y, y_pred)
f1          = f1_score(y, y_pred)
mcc         = matthews_corrcoef(y, y_pred)
auc_score   = roc_auc_score(y, y_pred_prob)

print("\n================ Self-Consistency Results (Siamese Contrastive - 100% Training) ================")
print(f"Accuracy    : {accuracy*100:.4f}%")
print(f"Sensitivity : {sensitivity*100:.4f}%")
print(f"Specificity : {specificity*100:.4f}%")
print(f"Precision   : {precision*100:.4f}%")
print(f"F1-score    : {f1*100:.4f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("================================================================================================")

# ----------------------------------------------------------------------
# 8. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_siamese, tpr_siamese, thresholds_siamese = roc_curve(y, y_pred_prob)
roc_auc_siamese = auc(fpr_siamese, tpr_siamese)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_siamese,
    tpr_siamese,
    color="teal",
    lw=2,
    label=f"Siamese Self-Consistency (AUC = {roc_auc_siamese:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Siamese Contrastive (Self-Consistency)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_Siamese_Contrastive_SelfConsistency.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 9. Save Metrics to CSV and ROC variables to NPZ
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "Siamese_Contrastive_SelfConsistency",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_siamese,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("Siamese_Contrastive_SelfConsistency_Results.csv", index=False)

np.savez(
    "roc_values_siamese.npz",
    fpr_siamese=fpr_siamese,
    tpr_siamese=tpr_siamese,
    roc_auc_siamese=roc_auc_siamese,
)

print("\nSaved: Siamese_Contrastive_SelfConsistency_Results.csv")
print("Saved: ROC_Siamese_Contrastive_SelfConsistency.png")
print("Saved: roc_values_siamese.npz")



"""
Mamba-2 (Selective State-Space Model) - Pure Self-Consistency (100% Dataset Training)
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Strategy: Pure Self-Consistency Evaluation (100% Dataset for Training & Evaluation)
          No independent test split, No K-Fold Cross Validation.
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_mamba, tpr_mamba, roc_auc_mamba

Architecture Details:
    1. Arcsinh feature transformation for extreme dynamic range stability.
    2. CNN front-end for sequence feature projection.
    3. Custom Mamba-2 Selective State-Space (SSM) Blocks with scalar-per-channel
       A matrix discretization and input-dependent delta, B, and C parameters.
    4. Evaluated on 100% of dataset to establish upper-bound self-consistency metrics.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ----------------------------------------------------------------------
# 1. Load Data (100% used for Self-Consistency)
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"   # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int32")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# arcsinh scaling (signed log) handles high dynamic range PVC features
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Feature Scaling & Reshaping (Fit on entire dataset)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype("float32")

# Reshape to (samples, timesteps, channels) for Conv1D front-end
X_scaled = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1], 1)
n_features = X_scaled.shape[1]

# ----------------------------------------------------------------------
# 3. Mamba-2 Block (Selective SSM with scalar-per-channel A)
# ----------------------------------------------------------------------
class Mamba2Block(layers.Layer):
    def __init__(self, d_model, d_state=16, d_conv=4, expand=2, **kwargs):
        super().__init__(**kwargs)
        self.d_model = d_model
        self.d_state = d_state
        self.d_conv = d_conv
        self.d_inner = expand * d_model

    def build(self, input_shape):
        self.in_proj = layers.Dense(2 * self.d_inner, use_bias=False, name="in_proj")
        self.conv1d = layers.Conv1D(
            filters=self.d_inner, kernel_size=self.d_conv,
            padding="causal", groups=self.d_inner, activation=None, name="short_conv"
        )
        self.x_proj = layers.Dense(1 + 2 * self.d_state, use_bias=False, name="x_proj")
        self.dt_proj = layers.Dense(self.d_inner, use_bias=True, name="dt_proj")

        # Mamba-2: A is a single learnable SCALAR per channel
        self.A_log = self.add_weight(
            shape=(self.d_inner,), initializer=tf.keras.initializers.Constant(0.0),
            trainable=True, name="A_log"
        )
        self.D = self.add_weight(
            shape=(self.d_inner,), initializer="ones", trainable=True, name="skip_D"
        )
        self.out_proj = layers.Dense(self.d_model, use_bias=False, name="out_proj")
        super().build(input_shape)

    def call(self, x):
        seq_len = tf.shape(x)[1]

        x_and_res = self.in_proj(x)
        x_in, res = tf.split(x_and_res, 2, axis=-1)

        x_in = self.conv1d(x_in)[:, :seq_len, :]
        x_in = tf.nn.silu(x_in)

        x_dbl = self.x_proj(x_in)
        delta, B, C = tf.split(x_dbl, [1, self.d_state, self.d_state], axis=-1)
        delta = tf.nn.softplus(self.dt_proj(delta))

        A = -tf.exp(self.A_log)

        deltaA = tf.exp(delta * A)
        deltaB_u = (delta * x_in)[..., None] * B[:, :, None, :]

        deltaA_seq = tf.transpose(deltaA, [1, 0, 2])
        deltaBu_seq = tf.transpose(deltaB_u, [1, 0, 2, 3])

        def scan_step(h_prev, elems):
            dA_t, dBu_t = elems
            return dA_t[..., None] * h_prev + dBu_t

        h0 = tf.zeros((tf.shape(x)[0], self.d_inner, self.d_state), dtype=x.dtype)
        hs = tf.scan(scan_step, (deltaA_seq, deltaBu_seq), initializer=h0)
        hs = tf.transpose(hs, [1, 0, 2, 3])

        y = tf.reduce_sum(hs * C[:, :, None, :], axis=-1)
        y = y + x_in * self.D
        y = y * tf.nn.silu(res)
        return self.out_proj(y)

    def get_config(self):
        config = super().get_config()
        config.update({
            "d_model": self.d_model, "d_state": self.d_state,
            "d_conv": self.d_conv, "expand": self.d_inner // self.d_model,
        })
        return config


# ----------------------------------------------------------------------
# 4. Build Mamba-2 Hybrid Model Architecture
# ----------------------------------------------------------------------
def build_mamba2_self_consistency(input_len, d_model=128, d_state=16, n_blocks=3):
    inputs = layers.Input(shape=(input_len, 1))

    # CNN Front-end: Feature Extraction
    x = layers.Conv1D(64, kernel_size=7, padding="same", activation="relu")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    x = layers.Conv1D(128, kernel_size=5, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    # Project into Mamba-2 dimension
    x = layers.Dense(d_model)(x)

    # Selective State-Space Backbone
    for _ in range(n_blocks):
        residual = x
        x = layers.LayerNormalization(epsilon=1e-6)(x)
        x = Mamba2Block(d_model=d_model, d_state=d_state)(x)
        x = x + residual

    x = layers.LayerNormalization(epsilon=1e-6)(x)
    x = layers.GlobalAveragePooling1D()(x)

    x = layers.Dense(128, activation="relu")(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    mamba2 = models.Model(inputs, outputs, name="Mamba2_SelfConsistency")
    mamba2.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return mamba2


mamba2 = build_mamba2_self_consistency(n_features)
mamba2.summary()

# ----------------------------------------------------------------------
# 5. Train Model on 100% of Dataset (Self-Consistency)
# ----------------------------------------------------------------------
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="loss", factor=0.5, patience=5, min_lr=1e-6
)

print("\nStarting Mamba-2 Training on 100% Dataset for Self-Consistency...")
history = mamba2.fit(
    X_scaled, y,
    batch_size=32,
    epochs=100,
    callbacks=[reduce_lr],
    verbose=2,
)

# ----------------------------------------------------------------------
# 6. Evaluate Self-Consistency
# ----------------------------------------------------------------------
y_pred_prob = mamba2.predict(X_scaled, batch_size=256).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()

accuracy    = accuracy_score(y, y_pred)
sensitivity = recall_score(y, y_pred)
specificity = tn / (tn + fp)
precision   = precision_score(y, y_pred)
f1          = f1_score(y, y_pred)
mcc         = matthews_corrcoef(y, y_pred)
auc_score   = roc_auc_score(y, y_pred_prob)

print("\n================ Self-Consistency Results (Mamba-2 - 100% Training) ================")
print(f"Accuracy    : {accuracy*100:.4f}%")
print(f"Sensitivity : {sensitivity*100:.4f}%")
print(f"Specificity : {specificity*100:.4f}%")
print(f"Precision   : {precision*100:.4f}%")
print(f"F1-score    : {f1*100:.4f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("====================================================================================")

# ----------------------------------------------------------------------
# 7. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_mamba, tpr_mamba, thresholds_mamba = roc_curve(y, y_pred_prob)
roc_auc_mamba = auc(fpr_mamba, tpr_mamba)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_mamba,
    tpr_mamba,
    color="purple",
    lw=2,
    label=f"Mamba-2 Self-Consistency (AUC = {roc_auc_mamba:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Mamba-2 (Self-Consistency)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_Mamba2_SelfConsistency.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 8. Save Metrics to CSV and ROC variables to NPZ
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "Mamba2_SelfConsistency",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_mamba,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("Mamba2_SelfConsistency_Results.csv", index=False)

np.savez(
    "roc_values_mamba2.npz",
    fpr_mamba=fpr_mamba,
    tpr_mamba=tpr_mamba,
    roc_auc_mamba=roc_auc_mamba,
)

print("\nSaved: Mamba2_SelfConsistency_Results.csv")
print("Saved: ROC_Mamba2_SelfConsistency.png")
print("Saved: roc_values_mamba2.npz")



"""
xLSTM (Extended Long Short-Term Memory) - Pure Self-Consistency (100% Dataset Training)
================================================================================
Dataset : Glycometabolic PVC + ESM-2 features (1433 features + Label)
Strategy: Pure Self-Consistency Evaluation (100% Dataset for Training & Evaluation)
          No independent test split, No K-Fold Cross Validation.
Batch   : 32
Epochs  : 100
Outputs : Accuracy, Sensitivity(Recall), Specificity, Precision, F1, MCC, AUC
          + ROC curve variables: fpr_xlstm, tpr_xlstm, roc_auc_xlstm

Activation Updates:
    - Standard ReLU (`nn.ReLU`) activations for updates.
    - Standardized traditional Sigmoid gating (`torch.sigmoid`) for output gates
      and classification activation probabilities.
"""

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, matthews_corrcoef, confusion_matrix,
                             roc_curve, auc, roc_auc_score)

# ----------------------------------------------------------------------
# 0. Reproducibility
# ----------------------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ----------------------------------------------------------------------
# 1. Load Data (100% used for Self-Consistency)
# ----------------------------------------------------------------------
DATA_PATH = "/content/GulcoMetabolismESM2_650M_1280Dver27.csv"  # update path if needed
df = pd.read_csv(DATA_PATH)

feature_cols = [c for c in df.columns if c != "Label"]
X = df[feature_cols].values.astype("float64")
y = df["Label"].values.astype("int64")

print(f"Feature matrix : {X.shape}")
print(f"Label counts   : {np.bincount(y)}")

# Defensive NaN/inf handling
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

# PVC descriptors stabilization via signed-log (arcsinh)
X = np.arcsinh(X).astype("float32")

# ----------------------------------------------------------------------
# 2. Feature Scaling (Fit on entire dataset)
# ----------------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype("float32")
n_features = X_scaled.shape[1]

# Convert to PyTorch Tensors
X_t = torch.tensor(X_scaled, dtype=torch.float32)
y_t = torch.tensor(y, dtype=torch.long)

dataset = TensorDataset(X_t, y_t)
data_loader = DataLoader(dataset, batch_size=32, shuffle=True)
eval_loader = DataLoader(dataset, batch_size=256, shuffle=False)

# ----------------------------------------------------------------------
# 3. xLSTM Architecture Components
# ----------------------------------------------------------------------
class sLSTMCell(nn.Module):
    """sLSTM cell with exponential gating, ReLU cell updates, and Sigmoid output gating."""
    def __init__(self, hidden_dim):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.w_i = nn.Linear(hidden_dim, hidden_dim)
        self.w_f = nn.Linear(hidden_dim, hidden_dim)
        self.w_o = nn.Linear(hidden_dim, hidden_dim)
        self.w_z = nn.Linear(hidden_dim, hidden_dim)

        self.r_i = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.r_f = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.r_o = nn.Linear(hidden_dim, hidden_dim, bias=False)
        self.r_z = nn.Linear(hidden_dim, hidden_dim, bias=False)

    def forward(self, x, state=None):
        batch_size, seq_len, _ = x.shape
        if state is None:
            h = torch.zeros(batch_size, self.hidden_dim, device=x.device)
            c = torch.zeros(batch_size, self.hidden_dim, device=x.device)
            n = torch.zeros(batch_size, self.hidden_dim, device=x.device)
            m = torch.zeros(batch_size, self.hidden_dim, device=x.device)
        else:
            h, c, n, m = state

        outputs = []
        for t in range(seq_len):
            x_t = x[:, t, :]

            # Gating projections
            i_tilde = self.w_i(x_t) + self.r_i(h)
            f_tilde = self.w_f(x_t) + self.r_f(h)
            o_tilde = self.w_o(x_t) + self.r_o(h)

            # ReLU cell candidate modulation
            z_t     = F.relu(self.w_z(x_t) + self.r_z(h))

            # Stabilized exponential gates & Sigmoid output gate
            m_next = torch.maximum(f_tilde + m, i_tilde)
            i_gate = torch.exp(i_tilde - m_next)
            f_gate = torch.exp(f_tilde + m - m_next)
            o_gate = torch.sigmoid(o_tilde)

            c = f_gate * c + i_gate * z_t
            n = f_gate * n + i_gate
            m = m_next

            # ReLU output state activation normalized by state tracking
            h = o_gate * F.relu(c / torch.clamp(n, min=1e-6))
            outputs.append(h.unsqueeze(1))

        outputs = torch.cat(outputs, dim=1)
        return outputs, (h, c, n, m)


class mLSTMCell(nn.Module):
    """mLSTM cell with matrix memory key-value retrieval and Sigmoid gating."""
    def __init__(self, hidden_dim, num_heads=8):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = hidden_dim // num_heads

        self.q_proj = nn.Linear(hidden_dim, hidden_dim)
        self.k_proj = nn.Linear(hidden_dim, hidden_dim)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)

        self.i_gate = nn.Linear(hidden_dim, num_heads)
        self.f_gate = nn.Linear(hidden_dim, num_heads)
        self.o_gate = nn.Linear(hidden_dim, hidden_dim)

        self.out_proj = nn.Linear(hidden_dim, hidden_dim)

    def forward(self, x):
        batch_size, seq_len, _ = x.shape

        Q = self.q_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim)
        K = self.k_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim) / np.sqrt(self.head_dim)
        V = self.v_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim)

        i = torch.exp(self.i_gate(x))
        f = torch.sigmoid(self.f_gate(x))
        o = torch.sigmoid(self.o_gate(x))

        C = torch.zeros(batch_size, self.num_heads, self.head_dim, self.head_dim, device=x.device)
        outputs = []

        for t in range(seq_len):
            q_t = Q[:, t]
            k_t = K[:, t]
            v_t = V[:, t]
            i_t = i[:, t].unsqueeze(-1).unsqueeze(-1)
            f_t = f[:, t].unsqueeze(-1).unsqueeze(-1)

            kv_outer = torch.matmul(k_t.unsqueeze(-1), v_t.unsqueeze(-2))
            C = f_t * C + i_t * kv_outer

            h_t = torch.matmul(q_t.unsqueeze(-2), C).squeeze(-2)
            h_flat = h_t.view(batch_size, self.hidden_dim)
            outputs.append(h_flat.unsqueeze(1))

        out = torch.cat(outputs, dim=1) * o
        return self.out_proj(out)


class xLSTMBlock(nn.Module):
    def __init__(self, hidden_dim, num_heads=8):
        super().__init__()
        self.ln1 = nn.LayerNorm(hidden_dim)
        self.mlstm = mLSTMCell(hidden_dim, num_heads=num_heads)
        self.ln2 = nn.LayerNorm(hidden_dim)
        self.slstm = sLSTMCell(hidden_dim)

        self.ffn = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim * 4),
            nn.ReLU(),
            nn.Linear(hidden_dim * 4, hidden_dim)
        )

    def forward(self, x):
        x = x + self.mlstm(self.ln1(x))
        s_out, _ = self.slstm(self.ln2(x))
        x = x + s_out
        x = x + self.ffn(x)
        return x


class xLSTMClassifier(nn.Module):
    def __init__(self, input_dim, seq_len=16, hidden_dim=256, num_classes=2):
        super().__init__()
        self.seq_len = seq_len
        self.chunk_dim = input_dim // seq_len
        self.remainder = input_dim % seq_len

        # Token projection
        self.input_proj = nn.Linear(self.chunk_dim + (1 if self.remainder > 0 else 0), hidden_dim)

        # Deep xLSTM Network
        self.xlstm1 = xLSTMBlock(hidden_dim, num_heads=8)
        self.xlstm2 = xLSTMBlock(hidden_dim, num_heads=8)
        self.xlstm3 = xLSTMBlock(hidden_dim, num_heads=8)

        # Classification Head
        self.head = nn.Sequential(
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        batch_size = x.size(0)

        if self.remainder > 0:
            pad_size = self.seq_len - self.remainder
            x_padded = F.pad(x, (0, pad_size))
        else:
            x_padded = x

        chunks = x_padded.view(batch_size, self.seq_len, -1)
        tokens = self.input_proj(chunks)

        x_rec = self.xlstm1(tokens)
        x_rec = self.xlstm2(x_rec)
        x_rec = self.xlstm3(x_rec)

        pooled = torch.mean(x_rec, dim=1) + torch.max(x_rec, dim=1)[0]
        logits = self.head(pooled)
        return logits


# Instantiation
model = xLSTMClassifier(input_dim=n_features, seq_len=16, hidden_dim=256).to(device)
print(model)

# ----------------------------------------------------------------------
# 4. Model Training Setup (100% Training Dataset)
# ----------------------------------------------------------------------
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", factor=0.5, patience=5
)

epochs = 100
print("\nStarting xLSTM Training on 100% Dataset for Self-Consistency...")

for epoch in range(1, epochs + 1):
    model.train()
    train_loss = 0.0
    for batch_X, batch_y in data_loader:
        batch_X, batch_y = batch_X.to(device), batch_y.to(device)

        optimizer.zero_grad()
        logits = model(batch_X)
        loss = criterion(logits, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        train_loss += loss.item() * batch_X.size(0)

    train_loss /= len(data_loader.dataset)
    scheduler.step(train_loss)

    if epoch % 10 == 0 or epoch == 1:
        current_lr = optimizer.param_groups[0]["lr"]
        print(f"Epoch {epoch:03d}/{epochs} | Loss: {train_loss:.4f} | LR: {current_lr:.6f}")

# ----------------------------------------------------------------------
# 5. Evaluate Self-Consistency
# ----------------------------------------------------------------------
model.eval()
all_preds = []
all_probs = []

with torch.no_grad():
    for batch_X, _ in eval_loader:
        batch_X = batch_X.to(device)
        logits = model(batch_X)
        probs = F.softmax(logits, dim=1)

        preds = torch.argmax(probs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_probs.extend(probs[:, 1].cpu().numpy())

y_pred = np.array(all_preds)
y_pred_prob = np.array(all_probs)

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()

accuracy    = accuracy_score(y, y_pred)
sensitivity = recall_score(y, y_pred)
specificity = tn / (tn + fp)
precision   = precision_score(y, y_pred)
f1          = f1_score(y, y_pred)
mcc         = matthews_corrcoef(y, y_pred)
auc_score   = roc_auc_score(y, y_pred_prob)

print("\n================ Self-Consistency Results (xLSTM - 100% Training) ================")
print(f"Accuracy    : {accuracy*100:.4f}%")
print(f"Sensitivity : {sensitivity*100:.4f}%")
print(f"Specificity : {specificity*100:.4f}%")
print(f"Precision   : {precision*100:.4f}%")
print(f"F1-score    : {f1*100:.4f}%")
print(f"MCC         : {mcc:.4f}")
print(f"AUC         : {auc_score:.4f}")
print(f"Confusion Matrix -> TN:{tn} FP:{fp} FN:{fn} TP:{tp}")
print("==================================================================================")

# ----------------------------------------------------------------------
# 6. ROC Curve Plotting and Variable Export
# ----------------------------------------------------------------------
fpr_xlstm, tpr_xlstm, thresholds_xlstm = roc_curve(y, y_pred_prob)
roc_auc_xlstm = auc(fpr_xlstm, tpr_xlstm)

plt.figure(figsize=(6, 6))
plt.plot(
    fpr_xlstm,
    tpr_xlstm,
    color="darkorange",
    lw=2,
    label=f"xLSTM Self-Consistency (AUC = {roc_auc_xlstm:.4f})",
)
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - xLSTM Network (Self-Consistency)\nPVC + ESM-2 Features")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("ROC_xLSTM_SelfConsistency.png", dpi=300)
plt.show()

# ----------------------------------------------------------------------
# 7. Save Metrics to CSV and ROC variables to NPZ
# ----------------------------------------------------------------------
results_df = pd.DataFrame([{
    "Model": "xLSTM_SelfConsistency",
    "Accuracy": accuracy,
    "Sensitivity": sensitivity,
    "Specificity": specificity,
    "Precision": precision,
    "F1_score": f1,
    "MCC": mcc,
    "AUC": roc_auc_xlstm,
    "TN": tn, "FP": fp, "FN": fn, "TP": tp,
}])
results_df.to_csv("xLSTM_SelfConsistency_Results.csv", index=False)

np.savez(
    "roc_values_xlstm.npz",
    fpr_xlstm=fpr_xlstm,
    tpr_xlstm=tpr_xlstm,
    roc_auc_xlstm=roc_auc_xlstm,
)

print("\nSaved: xLSTM_SelfConsistency_Results.csv")
print("Saved: ROC_xLSTM_SelfConsistency.png")
print("Saved: roc_values_xlstm.npz")



import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, roc_auc

plt.figure(figsize=(7, 7))

# Model 1: Siamese Network
plt.plot(
    fpr_siamese,
    tpr_siamese,
    color="teal",
    lw=2.5,
    label=f"Siamese Contrastive (AUC = {roc_auc_siamese:.4f})"
)

# Model 2: xLSTM Network
plt.plot(
    fpr_xlstm,
    tpr_xlstm,
    color="darkorange",
    lw=2.5,
    label=f"xLSTM Network (AUC = {roc_auc_xlstm:.4f})"
)
# ==========================================================
# GRID
# ==========================================================

plt.grid(
    True,
    linestyle='--',
    alpha=0.4
)
# Random baseline
plt.plot([0, 1], [0, 1], color="navy", lw=1.5, linestyle="--", label="Baseline")

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Comparative ROC Curves-Independent Test (Gylcometabolic Protein)")
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("Merged_ROC_Comparison.png", dpi=300)
plt.show()

# ==========================================================

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import auc
# ==========================================================
# FULL HD FIGURE
# ==========================================================

plt.figure(
    figsize=(8,8),
    dpi=300
)
plt.plot(
    fpr_cnntransformer,
    tpr_cnntransformer,
    color="Pink",
    lw=2,
    label=f"CNN-Transformer (AUC = {roc_auc_cnntransformer:.4f})",
)

plt.plot(
    fpr_xlstm,
    tpr_xlstm,
    color="darkorange",
    lw=2,
    label=f"xLSTM(AUC = {roc_auc_xlstm:.4f})",
)

plt.plot(
    fpr_mamba,
    tpr_mamba,
    color="purple",
    lw=2,
    label=f"Mamba-2 (AUC = {roc_auc_mamba:.4f})",
)
plt.plot(
    fpr_siamese,
    tpr_siamese,
    color="black",
    lw=2,
    label=f"Siamese Contrastive (AUC = {roc_auc_siamese:.4f})",
)
plt.plot(
    fpr_capsule,
    tpr_capsule,
    color="crimson",
    lw=2,
    label=f"Capsule Hybrid Network (AUC = {roc_auc_capsule:.4f})",
)
plt.plot(
    fpr_kan,
    tpr_kan,
    color="green",
    lw=2,
    label=f"Kolmogorov–Arnold Network (AUC = {roc_auc_kan:.4f})",
)

# ==========================================================
# LABELS
# ==========================================================

plt.xlabel(
    'False Positive Rate',
    fontsize=12,
    fontweight='bold'
)

plt.ylabel(
    'True Positive Rate',
    fontsize=12,
    fontweight='bold'
)

plt.title(
    'Comparative ROC Curves-Self Consistency of ESM-2 (Gylcometabolic Protein)',
    fontsize=12,
    fontweight='bold'
)

# ==========================================================
# TICKS
# ==========================================================

plt.xticks(fontsize=14)

plt.yticks(fontsize=14)

# ==========================================================
# GRID
# ==========================================================

plt.grid(
    True,
    linestyle='--',
    alpha=0.4
)

# ==========================================================
# LEGEND
# ==========================================================

plt.legend(
    loc='lower right',
    fontsize=12,
    frameon=True
)

# ==========================================================
# SAVE FULL HD IMAGE
# ==========================================================

plt.savefig(
    "Merged_ROC_Curves_FullHD.png",
    dpi=600,
    bbox_inches='tight'
)

# ==========================================================
# SAVE PDF
# ==========================================================

plt.savefig(
    "Merged_ROC_Curves_FullHD.pdf",
    bbox_inches='tight'
)

# ==========================================================
# SHOW FIGURE
# ==========================================================

plt.show()